window.MESAHA_VERSION = {
  "app": "Mesaha İO",
  "version": "v581_yakupp",
  "build": 581,
  "visibleVersion": "V5.81 •Yakupp•",
  "shortVersion": "V5.81",
  "name": "Mesaha İO V5.81 •Yakupp•",
  "cacheName": "mio-app-v581-yakupp",
  "integrityId": "v581-seflik-entry-repair-r1",
  "builtAt": "2026-07-13T01:18:00+03:00",
  "notes": "Şeflik sekmesine girişte Drive yedekleme benzeri yükleniyor ekranı açılır; şeflik klasörü, üyeler, bölmeler ve ortak kayıtlar arka planda birlikte senkronize edilir; yerel görünen aktif şeflik sunucuda otomatik onarılır/kurucu üyeliği tamamlanır; internet yok veya 10 saniyede cevap yoksa bağlantı başarısız uyarısı verilip en son mevcut bilgiler gösterilir.",
  "assetVersion": "581",
  "latestVersion": "v581_yakupp",
  "latestBuild": 581,
  "currentBuild": 581,
  "minSupportedBuild": 409,
  "forceUpdate": false,
  "updateUrl": "./guncelle.html",
  "cleanUrl": "./temizle.html",
  "version_id": "v581_yakupp",
  "versionId": "v581_yakupp",
  "id": "v581_yakupp",
  "updated_at": "2026-07-13T01:18:00+03:00"
};
