window.MESAHA_VERSION = {
  "app": "Mesaha İO",
  "version": "v572_yakupp",
  "build": 572,
  "visibleVersion": "V5.72 •Yakupp•",
  "shortVersion": "V5.72",
  "name": "Mesaha İO V5.72 •Yakupp•",
  "cacheName": "mio-app-v572-yakupp",
  "integrityId": "v572-no-cutter-filter-fix-r1",
  "builtAt": "2026-07-12T18:05:00+03:00",
  "notes": "Kesimci filtresinde 'Kesimci kaydı yok' seçeneğinin Tümü filtresine geri atması düzeltildi. Filtre tıklaması özel korumaya alındı ve sürüm bütünlüğü güncellendi.",
  "assetVersion": "572",
  "latestVersion": "v572_yakupp",
  "latestBuild": 572,
  "currentBuild": 572,
  "minSupportedBuild": 409,
  "forceUpdate": false,
  "updateUrl": "./guncelle.html",
  "cleanUrl": "./temizle.html",
  "version_id": "v572_yakupp",
  "versionId": "v572_yakupp",
  "id": "v572_yakupp",
  "updated_at": "2026-07-12T18:05:00+03:00"
};
