window.MESAHA_VERSION = {
  "app": "Mesaha İO",
  "version": "v574_yakupp",
  "build": 574,
  "visibleVersion": "V5.74 •Yakupp•",
  "shortVersion": "V5.74",
  "name": "Mesaha İO V5.74 •Yakupp•",
  "cacheName": "mio-app-v574-yakupp",
  "integrityId": "v574-seflik-guide-sync-layout-r1",
  "builtAt": "2026-07-12T15:20:00+03:00",
  "notes": "Kılavuz yeni Şeflik Klasörü ve terminal kodu eşleme akışına göre güncellendi; Şeflik Mesahaları üste, Bölme Yönetimi alta taşındı; tek ve belirgin Kayıtları Senkronize Et düğmesi ortak klasör başlığına alındı.",
  "assetVersion": "574",
  "latestVersion": "v574_yakupp",
  "latestBuild": 574,
  "currentBuild": 574,
  "minSupportedBuild": 409,
  "forceUpdate": false,
  "updateUrl": "./guncelle.html",
  "cleanUrl": "./temizle.html",
  "version_id": "v574_yakupp",
  "versionId": "v574_yakupp",
  "id": "v574_yakupp",
  "updated_at": "2026-07-12T15:20:00+03:00"
};
