(function(){'use strict';
const K={
  session:'mesaha_supabase_v500_session',backup:'mesaha_supabase_v569_session_backup',access:'mesaha_google_access_v548',panel:'mesaha_panel_user_v316',settings:'cam_mesaha_ayarlar_v1',terminal:'mesaha_terminal_local_mode_v556',terminalOld:'mesaha_terminal_local_mode_v557',active:'mesaha_active_seflik_folder_v564',
  folderCache:'mesaha_suite_folder_cache_v4',oldFolderCache:'mesaha_suite_folder_cache_v2',foresters:'mesaha_suite_foresters_v4',divisions:'mesaha_suite_divisions_v4',divisionRecords:'mesaha_suite_division_records_v4',divisionReady:'mesaha_suite_division_ready_v4',pendingOps:'mesaha_suite_pending_ops_v4',lastServerSync:'mesaha_suite_last_server_sync_v4',
  mesahaFolderCache:'mesaha_seflik_folder_cache_v529',mesahaPendingDivisions:'mesaha_seflik_folder_pending_divisions_v530',mesahaLastBolme:'mesaha_seflik_folder_last_bolme_v529',istifShared:'shared-context-v034'
};
const $=id=>document.getElementById(id);
const clean=v=>String(v==null?'':v).trim().replace(/\s+/g,' ');
const fold=v=>clean(v).toLocaleLowerCase('tr-TR').replace(/ç/g,'c').replace(/ğ/g,'g').replace(/ı/g,'i').replace(/ö/g,'o').replace(/ş/g,'s').replace(/ü/g,'u').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
const stableKey=v=>fold(v)||('yerel-'+Date.now().toString(36));
const read=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const esc=v=>clean(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>new Date().toISOString();
let folders=[],foresters={},divisions={},divisionRecords={},divisionReady={},pendingOps=[],busy=false,cacheReady=false;

function session(){return read(K.session,null)||read(K.backup,null)||{}}
function access(){return read(K.access,{})||{}}
function panel(){return read(K.panel,{})||{}}
function settings(){return read(K.settings,{})||{}}
function terminal(){const t=read(K.terminal,null)||read(K.terminalOld,null)||{};return t&&t.active?t:{}}
function pairedTerminal(){const t=terminal();return !!(t.active&&t.source==='pair_code'&&(t.terminalCode||t.terminalToken||t.pairedUserId))}
function authType(){if(session().access_token||access().status==='approved')return'google';if(pairedTerminal())return'terminal';if(terminal().active)return'guest';return'none'}
function signedIn(){return authType()!=='none'}
function cloudIdentity(){return authType()==='google'||authType()==='terminal'}
function terminalAuth(){const t=terminal();return pairedTerminal()?{terminalCode:clean(t.terminalCode),terminalToken:clean(t.terminalToken),terminalPairedUserId:clean(t.pairedUserId),terminalPairedEmail:clean(t.pairedEmail)}:{}}
function identity(){const s=session(),a=access(),p=panel(),t=terminal(),st=settings(),u=s.user||{},m=u.user_metadata||{};return{type:authType(),userId:clean(u.id||a.user_id||a.userId||t.pairedUserId||t.terminalCode||t.deviceId||'local'),name:clean(p.googleFullName||p.name||a.name||a.canonical_name||t.name||m.full_name||m.name||u.email),email:clean(a.email||p.googleEmail||t.pairedEmail||u.email),avatar:clean(p.googleAvatarUrl||p.avatarUrl||a.avatar_url||a.picture||t.avatarUrl||m.avatar_url||m.picture),seflik:clean((read(K.active,{})||{}).seflik||p.activeSeflik||p.seflik||t.seflik||st.seflik),bolme:clean(p.bolmeNo||t.bolmeNo||st.bolmeNo)}}
function toast(msg,bad=false){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.toggle('bad',bad);el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3600)}
function openModal(id){closeModals(true);const back=$('modalBackdrop'),m=$(id);if(!back||!m)return;back.hidden=false;m.hidden=false;m.removeAttribute('hidden');back.removeAttribute('hidden');document.body.classList.add('modal-open');if(id==='seflikModal')renderSeflikModal();if(id==='ormanciModal')renderOrmanciModal();if(id==='bolmeModal')renderBolmeModal();setTimeout(()=>{try{const f=m.querySelector('input,button,textarea,select');if(f)f.focus({preventScroll:true})}catch{}},80)}
function closeModals(keepBody){document.querySelectorAll('.modal').forEach(x=>{x.hidden=true;x.setAttribute('hidden','')});const b=$('modalBackdrop');if(b){b.hidden=true;b.setAttribute('hidden','')}if(!keepBody)document.body.classList.remove('modal-open')}
function avatarHTML(url,name,cls='mini-avatar'){const initials=(clean(name)||'M').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'M';return url?`<span class="${cls}"><img src="${esc(url)}" alt=""></span>`:`<span class="${cls}">${esc(initials)}</span>`}
function loadLocal(){folders=read(K.folderCache,read(K.oldFolderCache,[]));if(!Array.isArray(folders))folders=[];foresters=read(K.foresters,{});divisions=read(K.divisions,{});divisionRecords=read(K.divisionRecords,{});divisionReady=read(K.divisionReady,{});pendingOps=read(K.pendingOps,[]);if(!Array.isArray(pendingOps))pendingOps=[]}
function saveLocal(){write(K.folderCache,folders);write(K.foresters,foresters);write(K.divisions,divisions);write(K.divisionRecords,divisionRecords);write(K.divisionReady,divisionReady);write(K.pendingOps,pendingOps);syncAppCaches()}
function op(type,payload){pendingOps.push({id:'op_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2),type,payload,createdAt:now()});write(K.pendingOps,pendingOps);try{window.MesahaSuiteSyncV7&&window.MesahaSuiteSyncV7.markDirty('suite',{type:type})}catch{}updatePendingBadge()}
function updatePendingBadge(){const dot=$('notificationDot');if(dot)dot.style.display=pendingOps.length?'block':'none'}
function normalizeFolder(raw){const name=clean(raw&& (raw.seflik||raw.name||raw.folderSeflik));if(!name)return null;return{...raw,seflik:name,seflik_key:clean(raw.seflik_key||raw.seflikKey)||stableKey(name),role:clean(raw.role||raw.member_role||'owner'),is_creator:raw.is_creator!==false&&(['owner','creator','kurucu',''].includes(clean(raw.role||'owner').toLocaleLowerCase('tr-TR'))),updatedAt:raw.updatedAt||raw.updated_at||now()}}
function creatorFolder(){return folders.find(f=>f&&!f.deleted&&(f.is_creator===true||['owner','creator','kurucu'].includes(clean(f.role).toLocaleLowerCase('tr-TR'))))||null}
function canManageFolder(f=activeFolder()){return !!(f&&(f.is_creator===true||['owner','creator','kurucu'].includes(clean(f.role).toLocaleLowerCase('tr-TR'))))}
function activeFolder(){const a=read(K.active,{}),id=identity();return folders.find(f=>f&&!f.deleted&&(clean(f.seflik_key||f.seflikKey)===clean(a.seflik_key||a.seflikKey)||clean(f.seflik).toLocaleLowerCase('tr-TR')===clean(id.seflik).toLocaleLowerCase('tr-TR')))||creatorFolder()||folders.find(f=>!f.deleted)||null}
function activeKey(){const f=activeFolder();return f?clean(f.seflik_key||f.seflikKey)||stableKey(f.seflik):''}
function setActive(f){f=normalizeFolder(f);if(!f)return;const sf=f.seflik,key=f.seflik_key;write(K.active,{seflik:sf,seflik_key:key,role:f.role||'',creator:!!f.is_creator,updatedAt:now()});const p=panel();p.seflik=sf;p.activeSeflik=sf;p.updatedAt=now();write(K.panel,p);const st=settings();st.seflik=sf;write(K.settings,st);try{window.dispatchEvent(new Event('mesaha:seflik-folder-active-changed'))}catch{}}
function folderList(){return folders.filter(f=>f&&!f.deleted)}
function currentForesters(){const k=activeKey();return Array.isArray(foresters[k])?foresters[k]:[]}
function currentDivisions(){const k=activeKey();return (Array.isArray(divisions[k])?divisions[k]:[]).filter(d=>d&&!d.deleted).sort((a,b)=>clean(a.bolme_no).localeCompare(clean(b.bolme_no),'tr',{numeric:true}))}
function readyKey(folderKey,bolme){return (folderKey||activeKey())+'::'+clean(bolme)}
function isDivisionReady(d){return !!(d&&(d.offline_ready||divisionReady[readyKey(d.seflik_key||activeKey(),d.bolme_no)]))}
async function edge(action,data={}){const api=window.mesahaSupabase;if(!api||typeof api.edge!=='function')throw new Error('Sunucu bağlantısı hazır değil.');return api.edge(action,{source:'mesaha-suite-v7',...terminalAuth(),...data})}
function localFolder(){const id=identity();if(!id.seflik||/^(Dosya|Şeflik seçilmedi)$/i.test(id.seflik))return null;return normalizeFolder({seflik:id.seflik,seflik_key:clean((read(K.active,{})||{}).seflik_key)||stableKey(id.seflik),role:'owner',is_creator:true,is_local:true})}
async function loadFolders(force=false){loadLocal();if(!signedIn()){folders=[];render();return folders}const lf=localFolder();if(lf&&!folders.some(f=>clean(f.seflik_key)===lf.seflik_key||clean(f.seflik).toLocaleLowerCase('tr-TR')===lf.seflik.toLocaleLowerCase('tr-TR')))folders.unshift(lf);if(!cloudIdentity()||navigator.onLine===false){if(!activeFolder()&&folders[0])setActive(folders[0]);render();return folders}try{const out=await edge('seflik_folder_list_my_sefliks',{seflik:identity().seflik,folderSeflik:identity().seflik});const remote=(Array.isArray(out.folders)?out.folders:[]).map(normalizeFolder).filter(Boolean);if(remote.length)folders=remote;else if(lf)folders=[lf];if(!activeFolder()&&folders[0])setActive(creatorFolder()||folders[0]);await loadMembersFromServer();await loadDivisionsFromServer();saveLocal();render();return folders}catch(e){if(force)toast('Şeflikler alınamadı: '+e.message,true);if(!activeFolder()&&folders[0])setActive(folders[0]);render();return folders}}
async function loadMembersFromServer(){const af=activeFolder();if(!af||!cloudIdentity()||navigator.onLine===false)return;try{const out=await edge('seflik_folder_list_members',{seflik:af.seflik,folderSeflik:af.seflik});const list=(Array.isArray(out.members)?out.members:[]).map(m=>({id:clean(m.user_id||m.id||m.member_user_id||m.email||m.name),userId:clean(m.user_id||m.member_user_id),name:clean(m.name||m.canonical_name||m.email),email:clean(m.email),avatarUrl:clean(m.avatar_url||m.avatarUrl),role:clean(m.role||m.member_role||'member'),isSelf:!!m.is_self,updatedAt:now()})).filter(x=>x.name);foresters[af.seflik_key]=list}catch{}}
async function loadDivisionsFromServer(){const af=activeFolder();if(!af||!cloudIdentity()||navigator.onLine===false)return;try{const out=await edge('seflik_folder_list',{seflik:af.seflik,folderSeflik:af.seflik});const list=(Array.isArray(out.divisions)?out.divisions:(Array.isArray(out.summaries)?out.summaries:[])).map(d=>normalizeDivision(d,af)).filter(Boolean);if(list.length){const old=currentDivisions();const merged=new Map();old.forEach(x=>merged.set(clean(x.bolme_no),x));list.forEach(x=>merged.set(clean(x.bolme_no),{...merged.get(clean(x.bolme_no)),...x}));divisions[af.seflik_key]=Array.from(merged.values())}}catch{}}
function normalizeDivision(raw,folder){folder=folder||activeFolder();const no=clean(raw&&(raw.bolme_no||raw.bolmeNo||raw.bolme));if(!no||!folder)return null;const k=folder.seflik_key||stableKey(folder.seflik);return{...raw,bolme_no:no,bolmeNo:no,seflik:folder.seflik,seflik_key:k,location:clean(raw.location||raw.mevki||raw.description),record_count:Number(raw.record_count||raw.recordCount||0)||0,total_volume:Number(raw.total_volume||raw.totalVolume||0)||0,created_by_name:clean(raw.created_by_name||raw.createdByName||identity().name),contributors:Array.isArray(raw.contributors)?raw.contributors:[],status:raw.status||'open',created_at:raw.created_at||raw.createdAt||now(),updated_at:raw.updated_at||raw.updatedAt||now(),offline_ready:!!(raw.offline_ready||divisionReady[readyKey(k,no)]),pending:!!raw.pending,local_pending:!!raw.local_pending}}
function syncAppCaches(){const af=activeFolder();if(!af){write(K.mesahaFolderCache,{at:now(),seflik:'',divisions:[]});write(K.mesahaPendingDivisions,{seflik:'',divisions:[]});try{localStorage.removeItem(K.mesahaLastBolme)}catch{};writeIstifSharedCache(null,[]).catch(()=>{});try{window.dispatchEvent(new CustomEvent('mesaha-suite:shared-data-updated',{detail:{seflik:'',divisions:[]}}))}catch{};return;}const k=af.seflik_key||stableKey(af.seflik),dvs=currentDivisions().map(d=>normalizeDivision(d,af)).filter(Boolean);const fNames=currentForesters().map(x=>x.name).filter(Boolean);write(K.mesahaFolderCache,{at:now(),seflik:af.seflik,divisions:dvs.map(d=>({bolme_no:d.bolme_no,status:'open',record_count:d.record_count||0,total_volume:d.total_volume||0,contributors:fNames,created_by_name:d.created_by_name||identity().name,created_at:d.created_at,updated_at:d.updated_at,drive_backed_up:!!d.drive_backed_up,local_pending:!!d.pending,offline_ready:isDivisionReady(d)}))});write(K.mesahaPendingDivisions,{seflik:af.seflik,divisions:dvs.filter(d=>d.pending).map(d=>({bolme_no:d.bolme_no,status:'open',local_pending:true,created_by_name:d.created_by_name||identity().name,created_at:d.created_at,updated_at:d.updated_at}))});const firstReady=dvs.find(isDivisionReady)||dvs[0];if(firstReady)localStorage.setItem(K.mesahaLastBolme,firstReady.bolme_no);writeIstifSharedCache(af,dvs,fNames).catch(()=>{});try{window.dispatchEvent(new CustomEvent('mesaha-suite:shared-data-updated',{detail:{seflik:af.seflik,divisions:dvs}}))}catch{}}
async function writeIstifSharedCache(af,dvs){try{if(!('indexedDB'in window))return;const req=indexedDB.open('mesaha-istif-prototype',1);await new Promise((res,rej)=>{req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('records'))db.createObjectStore('records',{keyPath:'id'});if(!db.objectStoreNames.contains('settings'))db.createObjectStore('settings',{keyPath:'key'})};req.onsuccess=res;req.onerror=()=>rej(req.error)});const db=req.result;const tx=db.transaction('settings','readwrite');const store=tx.objectStore('settings');const auth=identity(),key=af?clean(af.seflik_key||af.seflikKey):'',members=af?currentForesters():[];store.put({key:K.istifShared,value:{seflikler:folderList().map(f=>({name:f.seflik,key:f.seflik_key,role:f.role,isCreator:!!f.is_creator})),membersBySeflik:key?{[key]:members}:{},customForestersBySeflik:key?{[key]:members}:{},removedForestersBySeflik:{},suiteDivisions:Array.isArray(dvs)?dvs:[],drive:{},auth:{status:signedIn()?'cached':'signed_out',name:auth.name,email:auth.email,avatarUrl:auth.avatar,userId:auth.userId},updatedAt:now()}});await new Promise((res,rej)=>{tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});try{db.close()}catch{}}catch{}}
function render(){const id=identity(),has=signedIn(),t=id.type,af=activeFolder();const av=$('avatar');if(av)av.innerHTML=id.avatar?`<img src="${esc(id.avatar)}" alt="">`:esc((id.name||'M').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'M');$('profileName')&&($('profileName').textContent=has?(id.name||'Kullanıcı'):'Giriş yapılmadı');const office=$('profileOffice');if(office)office.lastChild.textContent=' '+(af?af.seflik:(id.seflik||'Şeflik seçilmedi'));$('loginButtonTitle')&&($('loginButtonTitle').textContent=has?'Oturum Bilgileri':'Giriş Yap');$('loginButtonSub')&&($('loginButtonSub').textContent=t==='google'?'Google hesabı bağlı':t==='terminal'?'Terminal kodu ile bağlı':t==='guest'?'Yerel misafir modu':'Google veya misafir modu');const cr=creatorFolder();$('seflikCardSub')&&($('seflikCardSub').textContent=cr?cr.seflik+' • kurucu':'Her kullanıcı yalnızca 1 şeflik');document.querySelectorAll('[data-app]').forEach(b=>{b.disabled=false;b.classList.toggle('is-locked',!has)});document.querySelectorAll('[data-modal="seflik"],[data-modal="ormanci"],[data-modal="bolme"]').forEach(b=>{b.disabled=false;b.classList.toggle('is-locked',!has)});$('connectionText')&&($('connectionText').textContent=navigator.onLine?'Çevrimiçi':'Çevrimdışı');$('connectionPill')&&$('connectionPill').classList.toggle('offline',!navigator.onLine);updatePendingBadge();renderAuthBox();renderOpenModals();syncAppCaches()}
function renderOpenModals(){if($('seflikModal')&&!$('seflikModal').hidden)renderSeflikModal();if($('ormanciModal')&&!$('ormanciModal').hidden)renderOrmanciModal();if($('bolmeModal')&&!$('bolmeModal').hidden)renderBolmeModal()}
function renderAuthBox(){const id=identity(),box=$('authSessionBox'),wrap=$('logoutWrap');if(!box||!wrap)return;if(!signedIn()){box.innerHTML='<div class="modal-note">Bir kez giriş yaptığınızda aynı oturum Mesaha İO ve İstif İO tarafından ortak kullanılır.</div>';wrap.innerHTML='';return}const label=id.type==='google'?'Google hesabı':id.type==='terminal'?'Kodla eşleşmiş terminal':'Yerel misafir';box.innerHTML=`<div class="auth-session-box profile-line">${avatarHTML(id.avatar,id.name)}<span><b>${esc(id.name||label)}</b><small>${esc(label)}${id.email?' • '+esc(id.email):''}${activeFolder()?' • '+esc(activeFolder().seflik):''}</small></span></div>`;wrap.innerHTML='<button class="danger-button" id="logoutBtn">Oturumu Kapat</button>';$('logoutBtn').onclick=logout}
function renderSeflikModal(){const form=$('seflikForm');if(!form)return;let box=$('currentSeflikBox');if(!box){box=document.createElement('div');box.id='currentSeflikBox';form.insertBefore(box,form.firstChild)}const list=folderList(),af=activeFolder(),cr=creatorFolder();const options=list.length?`<label class="suite-select-label">Aktif Şeflik<select id="suiteFolderSelectV6">${list.map((f,i)=>`<option value="${i}" ${af&&clean(f.seflik_key)===clean(af.seflik_key)?'selected':''}>${esc(f.seflik)}${canManageFolder(f)?' • kurucu':' • üye'}</option>`).join('')}</select></label>`:'<div class="modal-note">Henüz seçilebilecek şeflik yok.</div>';const current=af?`<div class="manager-card"><div><small>Aktif Şeflik</small><b>${esc(af.seflik)}</b><span>${canManageFolder(af)?'Bu şefliği yönetebilirsiniz.':'Bu şeflikte üyesiniz; yalnızca seçim yapabilirsiniz.'}</span></div>${canManageFolder(af)?`<div class="manager-actions"><button type="button" class="mini-button" data-action="rename-seflik">İsmini Düzenle</button><button type="button" class="mini-button danger-mini" data-action="delete-seflik">Şefliği Sil</button></div>`:''}</div>`:'';box.innerHTML=options+current;const sel=$('suiteFolderSelectV6');if(sel&&!sel.__bound){sel.__bound=true;sel.onchange=()=>selectFolder(Number(sel.value))}const inp=$('seflikName'),sub=$('seflikSubmit'),note=$('seflikLimitNote');if(inp){inp.disabled=!!cr;if(!cr)inp.value=''}if(sub){sub.disabled=!!cr;sub.textContent=cr?'Şeflik Zaten Var':'Şefliği Oluştur'}if(note){note.classList.toggle('warn',!!cr);note.textContent=cr?'Her kullanıcı yalnızca 1 şefliğin kurucusu olabilir. Üye olduğunuz diğer şeflikleri üstteki listeden seçebilirsiniz.':'Her kullanıcı yalnızca bir şefliğin kurucusu olabilir.'}}
async function selectFolder(index){const f=folderList()[index];if(!f)return;setActive(f);saveLocal();render();renderSeflikModal();if(cloudIdentity()&&navigator.onLine){toast('Şeflik bilgileri getiriliyor…');await loadMembersFromServer();await loadDivisionsFromServer();saveLocal();render();toast('Aktif şeflik değiştirildi.')}else toast('Aktif şeflik değiştirildi. Offline kayıtlar kullanılıyor.')}
function renderOrmanciModal(){const form=$('ormanciForm');if(!form)return;let list=$('ormanciCurrentList');if(!list){list=document.createElement('div');list.id='ormanciCurrentList';list.className='result-list current-list';form.insertBefore(list,$('ormanciSearch')?.closest('label')||form.firstChild)}const rows=currentForesters(),manage=canManageFolder();list.innerHTML='<div class="section-title"><b>Ekli Ormancılar</b><small>'+rows.length+' kişi</small></div>'+(rows.length?rows.map((m,i)=>`<div class="result-row person-row">${avatarHTML(m.avatarUrl,m.name)}<div class="grow"><b>${esc(m.name||'-')}</b><small>${esc(m.email||m.role||'Ormancı')}${m.pending?' • sunucu bekliyor':''}</small></div>${manage&&!m.isSelf&&!['owner','creator','kurucu'].includes(clean(m.role).toLocaleLowerCase('tr-TR'))?`<button class="mini-button danger-mini" type="button" data-remove-forester="${i}">Çıkar</button>`:''}</div>`).join(''):'<div class="modal-note">Henüz ormancı eklenmedi.</div>');const search=$('ormanciSearch')?.closest('label'),submit=form.querySelector('button[type="submit"]');if(search)search.hidden=!manage;if(submit)submit.hidden=!manage;let note=$('ormanciManagedNoteV6');if(!note){note=document.createElement('div');note.id='ormanciManagedNoteV6';note.className='modal-note';form.insertBefore(note,search||form.firstChild)}note.textContent=manage?'Ormancı ekleme ve çıkarma yalnızca Suite üzerinden yapılır.':'Bu şeflikte üyesiniz. Ormancı listesinden yalnızca uygulama içindeki seçimlerde yararlanabilirsiniz.'}
function renderBolmeModal(){const form=$('bolmeForm');if(!form)return;let list=$('bolmeCurrentList');if(!list){list=document.createElement('div');list.id='bolmeCurrentList';list.className='result-list current-list';form.insertBefore(list,form.querySelector('.form-actions')||null)}const rows=currentDivisions(),manage=canManageFolder();list.innerHTML='<div class="section-title"><b>Oluşturulan Bölmeler</b><small>'+rows.length+' bölme</small></div>'+(rows.length?rows.map((d,i)=>`<div class="result-row division-row"><span class="folder-dot ${isDivisionReady(d)?'ready':'wait'}">${isDivisionReady(d)?'✓':'↓'}</span><div class="grow"><b>Bölme ${esc(d.bolme_no)}</b><small>${isDivisionReady(d)?'Offline hazır':'Offline indirme gerekli'}${d.pending?' • sunucu bekliyor':''}${d.location?' • '+esc(d.location):''}</small></div><button class="mini-button" type="button" data-download-division="${i}">Offline İndir</button>${manage?`<button class="mini-button danger-mini" type="button" data-delete-division="${i}">Sil</button>`:''}</div>`).join(''):'<div class="modal-note">Henüz bölme oluşturulmadı.</div>')+'<button type="button" class="secondary-button wide-action" data-action="download-all-divisions">Tüm Bölmeleri Offline İndir</button>';form.querySelectorAll('label').forEach((el)=>{if(el.querySelector('#bolmeNo,#bolmeLocation'))el.hidden=!manage});const actions=form.querySelector('.form-actions');if(actions)actions.hidden=!manage;let note=$('bolmeManagedNoteV6');if(!note){note=document.createElement('div');note.id='bolmeManagedNoteV6';note.className='modal-note';form.insertBefore(note,form.firstChild)}note.textContent=manage?'Bölme oluşturma, silme ve offline indirme yalnızca Suite üzerinden yönetilir.':'Bu şeflikte üyesiniz. Bölmeleri silemez veya oluşturamazsınız; hazır bölmeleri indirebilirsiniz.'}
async function logout(){if(!confirm('Oturum kapatılsın mı? Yerel kayıtlar silinmez.'))return;try{if(authType()==='google'&&window.MesahaGoogleAuthV648)await window.MesahaGoogleAuthV648.logout()}catch{}[K.session,K.backup,K.access,K.terminal,K.terminalOld,K.folderCache,K.oldFolderCache].forEach(k=>localStorage.removeItem(k));folders=[];closeModals();render();toast('Oturum kapatıldı')}
async function openGoogle(){closeModals();try{await window.MesahaGoogleAuthV648.openGoogle()}catch(e){toast(e.message,true)}}
function openGuest(){closeModals();try{window.MesahaGoogleAuthV648.openTerminal()}catch(e){toast(e.message,true)}}
async function createSeflik(e){e.preventDefault();if(busy)return;const name=clean($('seflikName')&&$('seflikName').value);if(name.length<2)return toast('Şeflik adını yazın.',true);if(creatorFolder())return toast('Bu kullanıcı zaten bir şeflik oluşturmuş.',true);const f=normalizeFolder({seflik:name,seflik_key:stableKey(name),role:'owner',is_creator:true,is_local:authType()==='guest',createdAt:now()});folders=[f];foresters[f.seflik_key]=foresters[f.seflik_key]||[];divisions[f.seflik_key]=divisions[f.seflik_key]||[];setActive(f);op('create_seflik',{seflik:name,seflik_key:f.seflik_key});saveLocal();toast('Şeflik oluşturuldu. Sunucuya göndermek için Sunucuya Gönder butonunu kullanın.');render();renderSeflikModal()}
function renameSeflik(){if(!canManageFolder())return toast('Bu işlemi yalnızca şeflik kurucusu Suite üzerinden yapabilir.',true);const f=creatorFolder();if(!f)return;const next=clean(prompt('Yeni şeflik adı:',f.seflik));if(!next||next===f.seflik)return;const oldKey=f.seflik_key,oldName=f.seflik,newKey=stableKey(next);f.seflik=next;f.seflik_key=newKey;f.updatedAt=now();foresters[newKey]=foresters[oldKey]||[];divisions[newKey]=(divisions[oldKey]||[]).map(d=>({...d,seflik:next,seflik_key:newKey,updated_at:now()}));delete foresters[oldKey];delete divisions[oldKey];Object.keys(divisionReady).forEach(k=>{if(k.startsWith(oldKey+'::')){divisionReady[newKey+k.slice(oldKey.length)]=divisionReady[k];delete divisionReady[k]}});Object.keys(divisionRecords).forEach(k=>{if(k.startsWith(oldKey+'::')){divisionRecords[newKey+k.slice(oldKey.length)]=divisionRecords[k];delete divisionRecords[k]}});setActive(f);op('rename_seflik',{oldName,oldKey,newName:next,newKey});saveLocal();toast('Şeflik ismi yerelde düzenlendi.');render()}
function deleteSeflik(){if(!canManageFolder())return toast('Bu işlemi yalnızca şeflik kurucusu Suite üzerinden yapabilir.',true);const f=creatorFolder();if(!f)return;if(prompt(`${f.seflik} şefliği silinecek. Onay için şeflik adını yazın:`)!==f.seflik)return toast('Şeflik silinmedi.',true);folders=folders.filter(x=>x!==f);op('delete_seflik',{seflik:f.seflik,seflik_key:f.seflik_key});try{localStorage.removeItem(K.active)}catch{};saveLocal();toast('Şeflik silindi. Sunucuya Gönder ile buluttan da silinir.');render();renderSeflikModal()}
async function searchOrmanci(e){e.preventDefault();const q=clean($('ormanciSearch')&&$('ormanciSearch').value),box=$('ormanciResults');if(!box)return;if(q.length<3)return toast('En az 3 harf yazın.',true);if(!cloudIdentity()||navigator.onLine===false){box.innerHTML='<div class="modal-note warn">Ormancı araması için Google hesabı veya terminal kodu ve internet gerekir. Yerel ekleme için isim/e-posta yazıp tekrar deneyebilirsiniz.</div>';return}const af=activeFolder();if(!af)return toast('Önce şeflik oluşturun.',true);box.innerHTML='<div class="modal-note">Kullanıcılar aranıyor…</div>';try{const out=await edge('seflik_folder_search_users',{query:q,seflik:af.seflik});const users=Array.isArray(out.users)?out.users:[];box.innerHTML=users.length?users.map((u,i)=>`<div class="result-row person-row">${avatarHTML(clean(u.avatar_url||u.avatarUrl),u.name||u.email)}<div class="grow"><b>${esc(u.name||'-')}</b><small>${esc(u.email||'Google kullanıcısı')}</small></div><button class="mini-button" data-add-user-index="${i}">Ekle</button></div>`).join(''):'<div class="modal-note">Kullanıcı bulunamadı. Kişinin önce Google ile giriş yapması gerekir.</div>';box.querySelectorAll('[data-add-user-index]').forEach(b=>b.onclick=()=>addOrmanci(users[Number(b.dataset.addUserIndex)]||{},b))}catch(err){box.innerHTML='<div class="modal-note warn">'+esc(err.message)+'</div>'}}
function addOrmanci(u,btn){if(!canManageFolder())return toast('Bu işlemi yalnızca şeflik kurucusu Suite üzerinden yapabilir.',true);const af=activeFolder();if(!af)return;const k=af.seflik_key;const item={id:clean(u.user_id||u.userId||u.email||u.name)||('local_'+Date.now()),userId:clean(u.user_id||u.userId),name:clean(u.name||u.canonical_name||u.email||$('ormanciSearch')?.value),email:clean(u.email),avatarUrl:clean(u.avatar_url||u.avatarUrl||u.picture),role:'member',pending:true,updatedAt:now()};if(!item.name)return toast('Kullanıcı adı alınamadı.',true);const list=foresters[k]||[];if(list.some(x=>clean(x.id)===item.id||fold(x.name)===fold(item.name)))return toast('Bu ormancı zaten ekli.',true);foresters[k]=[...list,item];op('add_member',{seflik:af.seflik,seflik_key:k,member_user_id:item.userId,name:item.name,email:item.email,avatarUrl:item.avatarUrl});saveLocal();if(btn){btn.textContent='Eklendi';btn.disabled=true}toast('Ormancı eklendi.');render();renderOrmanciModal()}
function removeOrmanci(index){if(!canManageFolder())return toast('Bu işlemi yalnızca şeflik kurucusu Suite üzerinden yapabilir.',true);const af=activeFolder();if(!af)return;const k=af.seflik_key,list=foresters[k]||[],m=list[index];if(!m)return;if(!confirm(`${m.name} şeflikten çıkarılsın mı?`))return;foresters[k]=list.filter((_,i)=>i!==index);op('remove_member',{seflik:af.seflik,seflik_key:k,member_user_id:m.userId,name:m.name,email:m.email});saveLocal();toast('Ormancı çıkarıldı.');render();renderOrmanciModal()}
async function createBolme(e){if(!canManageFolder())return toast('Bu işlemi yalnızca şeflik kurucusu Suite üzerinden yapabilir.',true);e.preventDefault();const no=clean($('bolmeNo')&&$('bolmeNo').value),loc=clean($('bolmeLocation')&&$('bolmeLocation').value),af=activeFolder();if(!no)return toast('Bölme numarasını yazın.',true);if(!af)return toast('Önce şeflik oluşturun.',true);const k=af.seflik_key,list=divisions[k]||[];if(list.some(d=>clean(d.bolme_no)===no&&!d.deleted))return toast('Bu bölme zaten oluşturulmuş.',true);const d=normalizeDivision({bolme_no:no,location:loc,record_count:0,total_volume:0,pending:true,created_by_name:identity().name},af);divisions[k]=[d,...list];op('create_division',{seflik:af.seflik,seflik_key:k,bolmeNo:no,location:loc});const st=settings();st.bolmeNo=no;write(K.settings,st);const p=panel();p.bolmeNo=no;write(K.panel,p);saveLocal();toast('Bölme oluşturuldu, offline indiriliyor…');if($('bolmeNo'))$('bolmeNo').value='';if($('bolmeLocation'))$('bolmeLocation').value='';render();renderBolmeModal();await downloadDivisionByBolme(no,true)}
async function downloadDivision(idx,quiet=false){const d=currentDivisions()[idx];if(d)return downloadDivisionByBolme(d.bolme_no,quiet)}
async function downloadDivisionByBolme(no,quiet=false){const af=activeFolder();if(!af||!no)return;const k=af.seflik_key;let rows=[];if(cloudIdentity()&&navigator.onLine){try{const out=await edge('seflik_folder_read',{seflik:af.seflik,folderSeflik:af.seflik,bolmeNo:no});rows=Array.isArray(out.records)?out.records:[]}catch{rows=[]}}divisionRecords[readyKey(k,no)]=rows;divisionReady[readyKey(k,no)]={ready:true,at:now(),recordCount:rows.length};divisions[k]=(divisions[k]||[]).map(d=>clean(d.bolme_no)===clean(no)?{...d,offline_ready:true,record_count:Math.max(d.record_count||0,rows.length),updated_at:now()}:d);saveLocal();if(!quiet)toast('Bölme '+no+' offline kullanıma hazır.');render();renderBolmeModal()}
async function downloadAllDivisions(){const rows=currentDivisions();if(!rows.length)return toast('İndirilecek bölme yok.',true);for(const d of rows)await downloadDivisionByBolme(d.bolme_no,true);toast(rows.length+' bölme offline kullanıma hazır.');render()}
function deleteDivision(index){if(!canManageFolder())return toast('Bu işlemi yalnızca şeflik kurucusu Suite üzerinden yapabilir.',true);const af=activeFolder();if(!af)return;const k=af.seflik_key,list=divisions[k]||[],d=currentDivisions()[index];if(!d)return;if(prompt(`Bölme ${d.bolme_no} silinecek. Onay için bölme numarasını yazın:`)!==d.bolme_no)return toast('Bölme silinmedi.',true);divisions[k]=list.filter(x=>clean(x.bolme_no)!==clean(d.bolme_no));delete divisionReady[readyKey(k,d.bolme_no)];delete divisionRecords[readyKey(k,d.bolme_no)];op('delete_division',{seflik:af.seflik,seflik_key:k,bolmeNo:d.bolme_no});saveLocal();toast('Bölme silindi.');render();renderBolmeModal()}
async function sendPendingToServer(){if(!signedIn())return toast('Önce giriş yapın.',true);if(!cloudIdentity())return toast('Sunucuya göndermek için Google hesabı veya kodla eşleşmiş terminal gerekir.',true);if(!navigator.onLine)return toast('İnternet bağlantısı yok.',true);if(!pendingOps.length){toast('Gönderilecek yeni işlem yok.');await loadFolders(true);return}busy=true;toast('Sunucuya gönderiliyor…');const remain=[];for(const item of pendingOps){try{const p=item.payload||{};if(item.type==='create_seflik'){await edge('seflik_folder_create_seflik',{seflik:p.seflik})}else if(item.type==='delete_seflik'){await edge('seflik_folder_delete_seflik',{seflik:p.seflik,confirmSeflik:p.seflik})}else if(item.type==='rename_seflik'){await edge('seflik_folder_rename_seflik',{seflik:p.oldName,oldSeflik:p.oldName,newSeflik:p.newName,new_seflik:p.newName})}else if(item.type==='add_member'){if(!p.member_user_id)throw new Error('Ormancı için Google kullanıcı id yok');await edge('seflik_folder_add_member',{seflik:p.seflik,member_user_id:p.member_user_id})}else if(item.type==='remove_member'){if(p.member_user_id)await edge('seflik_folder_remove_member',{seflik:p.seflik,member_user_id:p.member_user_id})}else if(item.type==='create_division'){await edge('seflik_folder_create_division',{seflik:p.seflik,bolmeNo:p.bolmeNo,location:p.location||''})}else if(item.type==='delete_division'){await edge('seflik_folder_delete_division',{seflik:p.seflik,bolmeNo:p.bolmeNo,confirmBolme:p.bolmeNo,permanent:true})}}catch(e){item.error=String(e&&e.message?e.message:e);remain.push(item)}}pendingOps=remain;write(K.pendingOps,pendingOps);write(K.lastServerSync,{at:now(),remaining:pendingOps.length});await loadFolders(true);busy=false;toast(pendingOps.length?'Bazı işlemler beklemede kaldı. Durum ekranından bakabilirsiniz.':'Tüm yeni işlemler sunucuya gönderildi.',!!pendingOps.length);render()}
async function pingAdminProfile(){if(!navigator.onLine||!cloudIdentity()||!signedIn())return;const id=identity(),af=activeFolder();try{await edge('profile_ping_suite',{name:id.name||id.email||'Kullanıcı',seflik:af?.seflik||id.seflik||'',bolmeNo:id.bolme||'',appVersion:'Mesaha Suite V7',avatarUrl:id.avatar||'',deviceId:localStorage.getItem('mesaha_suite_device_v7')||(()=>{const x='suite_'+Math.random().toString(36).slice(2)+Date.now().toString(36);localStorage.setItem('mesaha_suite_device_v7',x);return x})(),deviceInfo:{appId:'suite',appName:'Mesaha Suite',platform:navigator.platform||'',browser:navigator.userAgent||'',suiteVersion:'V7'}})}catch{}}
async function syncNow(){if(!signedIn())return toast('Önce giriş yapın.',true);if(!navigator.onLine)return toast('İnternet bağlantısı yok.',true);toast('Şeflik bilgileri güncelleniyor…');await loadFolders(true);toast('Şeflik bilgileri güncellendi.')}
function showInfo(title,html,k='BİLGİ'){$('infoModalTitle').textContent=title;$('infoKicker').textContent=k;$('infoContent').innerHTML=html;openModal('infoModal')}
async function cleanupNestedWorkers(){if(!('serviceWorker'in navigator))return;try{const regs=await navigator.serviceWorker.getRegistrations();const rootScope=new URL('./',location.href).href;for(const reg of regs){const scope=String(reg.scope||'');if(scope!==rootScope&&(scope.includes('/test/mesaha/')||scope.includes('/test/istif/')))await reg.unregister()}}catch{}}
function workerMessage(worker,type,timeout=45000){return new Promise(resolve=>{if(!worker)return resolve({ready:false});const ch=new MessageChannel(),t=setTimeout(()=>resolve({ready:false,timeout:true}),timeout);ch.port1.onmessage=e=>{clearTimeout(t);resolve(e.data||{ready:false})};try{worker.postMessage({type},[ch.port2])}catch{clearTimeout(t);resolve({ready:false})}})}
async function prepareOffline(){if(!('serviceWorker'in navigator)){setCacheStatus('Tarayıcı desteklemiyor',0);return false}try{await cleanupNestedWorkers();try{if(navigator.storage&&navigator.storage.persist)await navigator.storage.persist()}catch{}const reg=await navigator.serviceWorker.register('./service-worker.js?v=7',{scope:'./',updateViaCache:'none'});await navigator.serviceWorker.ready;const worker=reg.active||navigator.serviceWorker.controller;setCacheStatus('Mesaha İO ve İstif İO dosyaları doğrulanıyor…',18);let st=await workerMessage(worker,'GET_STATUS',12000);if(!st.ready){setCacheStatus('Eksik uygulama dosyaları indiriliyor…',35);st=await workerMessage(worker,'CACHE_ALL',90000)}cacheReady=!!st.ready;if(cacheReady)setCacheStatus('İki uygulama kalıcı olarak çevrimdışı kullanıma hazır',100);else setCacheStatus(`Offline hazırlık eksik • ${Number(st.missingCount||st.missing?.length||0)} dosya`,78);return cacheReady}catch(e){setCacheStatus('Offline hazırlık tamamlanamadı',20);return false}}
function setCacheStatus(text,pct){$('lastSync')&&($('lastSync').textContent=text);$('cacheToolText')&&($('cacheToolText').textContent=pct>=100?'İki uygulama hazır':'Dosyalar hazırlanıyor');const bar=$('cacheProgressBar');if(bar)bar.style.width=Math.max(0,Math.min(100,pct))+'%';$('lastSync')&&$('lastSync').classList.toggle('offline-ready',pct>=100)}
function ensureLoginThen(fn){if(!signedIn()){openModal('loginModal');toast('Önce Google veya misafir modu ile giriş yapın.',true);return false}try{fn&&fn()}catch(e){toast(e.message||String(e),true)}return true}
function openSeflikModal(){return ensureLoginThen(()=>openModal('seflikModal'))}
function openOrmanciModal(){return ensureLoginThen(()=>openModal('ormanciModal'))}
function openBolmeModal(){return ensureLoginThen(()=>openModal('bolmeModal'))}
async function goApp(app){if(!signedIn()){openModal('loginModal');toast('Uygulamayı açmak için önce giriş yapın.',true);return}syncAppCaches();location.href=app==='mesaha'?'./mesaha/':'./istif/'}
function handleAction(target,ev){if(!target)return false;const modal=target.getAttribute('data-modal'),app=target.getAttribute('data-app'),tool=target.getAttribute('data-tool'),id=target.id,action=target.getAttribute('data-action');if(modal||app||tool||action||id==='profileAction'||id==='footerUpdate'||id==='notificationButton'||id==='googleLoginBtn'||id==='guestLoginBtn'||target.classList.contains('modal-close')||target.classList.contains('modal-cancel')){if(ev){ev.preventDefault();ev.stopPropagation()}}
  if(target.classList.contains('modal-close')||target.classList.contains('modal-cancel')){closeModals();return true}
  if(id==='profileAction'||modal==='login'||tool==='settings'){openModal('loginModal');return true}
  if(modal==='seflik')return openSeflikModal(),true;if(modal==='ormanci')return openOrmanciModal(),true;if(modal==='bolme')return openBolmeModal(),true;if(app){goApp(app);return true}
  if(tool==='sync'||tool==='server'){if(window.MesahaSuiteSyncV7)window.MesahaSuiteSyncV7.syncAll({source:tool}).then(()=>loadFolders(true)).catch(()=>{});else sendPendingToServer();return true}if(tool==='updates'||id==='footerUpdate'){prepareOffline();return true}if(tool==='backups'){window.MesahaSuiteBackupsV7&&window.MesahaSuiteBackupsV7.open();return true}
  if(tool==='admin'){location.href='./mesaha/yonetim/';return true}if(tool==='about'){showInfo('Mesaha Suite V7',`<p>Google veya terminal/misafir oturumu iki uygulamada ortak kullanılır.</p><p><b>Bekleyen işlem:</b> ${pendingOps.length}</p><p>Bölmeler offline indirildikten sonra Mesaha İO ve İstif İO’da kayıt eklemeye hazır olur.</p>`);return true}
  if(id==='notificationButton'){showInfo('Sistem Durumu',`<div class="info-stat"><span>Oturum</span><strong>${esc(authType())}</strong></div><div class="info-stat"><span>Şeflik</span><strong>${esc(activeFolder()?.seflik||'-')}</strong></div><div class="info-stat"><span>Ormancı</span><strong>${currentForesters().length}</strong></div><div class="info-stat"><span>Bölme</span><strong>${currentDivisions().length}</strong></div><div class="info-stat"><span>Sunucu bekleyen</span><strong>${pendingOps.length}</strong></div>`);return true}
  if(id==='googleLoginBtn'){openGoogle();return true}if(id==='guestLoginBtn'){openGuest();return true}
  if(action==='rename-seflik'){renameSeflik();return true}if(action==='delete-seflik'){deleteSeflik();return true}if(action==='download-all-divisions'){downloadAllDivisions();return true}
  if(target.dataset.removeForester!=null){removeOrmanci(Number(target.dataset.removeForester));return true}if(target.dataset.downloadDivision!=null){downloadDivision(Number(target.dataset.downloadDivision));return true}if(target.dataset.deleteDivision!=null){deleteDivision(Number(target.dataset.deleteDivision));return true}
  return false}
function bind(){document.addEventListener('click',ev=>{const t=ev.target&&ev.target.closest?ev.target.closest('button,[data-modal],[data-app],[data-tool],.modal-close,.modal-cancel'):null;handleAction(t,ev)},true);document.addEventListener('pointerup',ev=>{const t=ev.target&&ev.target.closest?ev.target.closest('button,[data-modal],[data-app],[data-tool],.modal-close,.modal-cancel'):null;if(t){try{t.blur()}catch{}}},{passive:true,capture:true});$('modalBackdrop').onclick=closeModals;$('seflikForm').onsubmit=createSeflik;$('ormanciForm').onsubmit=searchOrmanci;$('bolmeForm').onsubmit=createBolme;window.MesahaSuiteUI={openLogin:()=>openModal('loginModal'),openSeflik:openSeflikModal,openOrmanci:openOrmanciModal,openBolme:openBolmeModal,goApp,prepareOffline,sendPendingToServer,loadFolders,syncAppCaches,toast,openModal,closeModals};window.addEventListener('online',()=>{render();setTimeout(()=>loadFolders(true),0);setTimeout(pingAdminProfile,300)});window.addEventListener('offline',render);window.addEventListener('storage',()=>{loadLocal();render()});['mesaha:google-access-approved','mesaha:user-login','mesaha:terminal-mode-enabled'].forEach(n=>window.addEventListener(n,()=>setTimeout(()=>{loadLocal();render();loadFolders(true);pingAdminProfile()},80)));navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='CACHE_PROGRESS')setCacheStatus(e.data.text||'Dosyalar hazırlanıyor',e.data.percent||0);if(e.data?.type==='CACHE_READY'){cacheReady=true;setCacheStatus('Mesaha İO ve İstif İO çevrimdışı kullanıma hazır',100)}})}
async function init(){loadLocal();bind();render();setCacheStatus('Yerel veriler hazır • Offline denetimi arka planda',12);setTimeout(()=>prepareOffline(),120);if(location.hash&&/access_token=|error=/.test(location.hash)){try{await window.MesahaGoogleAuthV648.boot(true)}catch(e){toast(e.message,true)}}setTimeout(()=>loadFolders().then(render),40);setTimeout(pingAdminProfile,700)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();