window.MESAHA_VERSION = {
  "app": "Mesaha İO",
  "version": "v582_yakupp",
  "build": 582,
  "visibleVersion": "V5.82 •Yakupp•",
  "shortVersion": "V5.82",
  "name": "Mesaha İO V5.82 •Yakupp•",
  "cacheName": "mio-app-v582-yakupp",
  "integrityId": "v582-guest-seflik-lock-fix-r1",
  "builtAt": "2026-07-13T02:04:00+03:00",
  "notes": "Misafir/elle terminal modunda Şeflik Klasörü yükleniyor ekranında takılı kalması engellendi; Google veya terminal kodu yoksa sunucu senkronizasyonu başlatılmaz, yükleniyor penceresi kapanır ve kullanıcıya terminal kodu ya da Google girişi gerektiği gösterilir. Kodla eşleşmiş terminal ve Google oturumu olan cihazlarda mevcut şeflik senkronizasyonu çalışmaya devam eder.",
  "assetVersion": "582",
  "latestVersion": "v582_yakupp",
  "latestBuild": 582,
  "currentBuild": 582,
  "minSupportedBuild": 409,
  "forceUpdate": false,
  "updateUrl": "./guncelle.html",
  "cleanUrl": "./temizle.html",
  "version_id": "v582_yakupp",
  "versionId": "v582_yakupp",
  "id": "v582_yakupp",
  "updated_at": "2026-07-13T02:04:00+03:00"
};
