window.MESAHA_VERSION = {
  "app": "Mesaha İO",
  "version": "v583_yakupp",
  "build": 583,
  "visibleVersion": "V5.83 •Yakupp•",
  "shortVersion": "V5.83",
  "name": "Mesaha İO V5.83 •Yakupp•",
  "cacheName": "mio-app-v583-yakupp",
  "integrityId": "v583-mobile-focus-exact-sound-r1",
  "builtAt": "2026-07-14T22:15:00+03:00",
  "notes": "iOS’ta kaydet sonrası nadir klavye kapanmasına karşı ölçü alanı odak köprüsü güçlendirildi. Onay sesi yalnız paket içindeki gerçek WAV dosyasından çalacak şekilde tek motor altında düzeltildi; sentetik/başka bip kaldırıldı.",
  "assetVersion": "583",
  "latestVersion": "v583_yakupp",
  "latestBuild": 583,
  "currentBuild": 583,
  "minSupportedBuild": 409,
  "forceUpdate": false,
  "updateUrl": "./guncelle.html",
  "cleanUrl": "./temizle.html",
  "version_id": "v583_yakupp",
  "versionId": "v583_yakupp",
  "id": "v583_yakupp",
  "updated_at": "2026-07-14T22:15:00+03:00"
};
