/* Mesaha İO v169 Modüler Stabil - app-07.js */
/* Mesaha v139 - istatistik sıfırlama admin ana liste/özet kesin düzeltme */
(function(){
  "use strict";
  const BUILD_VERSION="Mesaha İO v1.98", FILE_VERSION="v139", MARKER="__stats_reset_marker__";
  const EXPORT_QUEUE="mesaha_export_stats_queue_v135", USAGE_LOCAL="mesaha_usage_stats_v128";
  const usageColl=()=>{try{return FIREBASE_USAGE_COLLECTION||"usageStats";}catch{return"usageStats";}};
  const usersColl=()=>{try{return FIREBASE_USERS_COLLECTION||"users";}catch{return"users";}};
  const toast=t=>{try{showToast?showToast(t):console.log(t);}catch{}};
  const n=v=>{const x=Number(String(v??"").replace(",",".").replace(/[^0-9.\-]/g,""));return Number.isFinite(x)?x:0;};
  const i=v=>Math.round(Number(v)||0).toLocaleString("tr-TR");
  const m3=v=>`${(Number(v)||0).toLocaleString("tr-TR",{minimumFractionDigits:3,maximumFractionDigits:3})} m³`;
  const dur=ms=>{try{if(typeof adminDurationTextV128==="function")return adminDurationTextV128(ms);}catch{}const min=Math.round((Number(ms)||0)/60000);return min?`${min} dk`:"0 dk";};
  const esc=v=>{try{return escapeHtml(v);}catch{return String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}};
  const today=()=>{const d=new Date(),p=x=>String(x).padStart(2,"0");return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`;};
  const genMs=d=>Number(d&&(d.exportAtMs||d.queuedAtMs||d.createdAtMs||d.generatedAtMs||d.updatedAtMs))||0;
  const localReset=()=>Number(localStorage.getItem("mesaha_stats_reset_at_v139")||localStorage.getItem("mesaha_stats_reset_at_v138")||localStorage.getItem("mesaha_stats_reset_at_v137")||0)||0;
  const setLocalReset=(r)=>{const ms=Number(r&&r.resetAtMs)||0;if(!ms)return;window.__mesahaStatsResetMarkerV139=r;try{localStorage.setItem("mesaha_stats_reset_at_v139",String(ms));localStorage.setItem("mesaha_stats_reset_at_v138",String(ms));}catch{}};
  const resetMs=()=>Number(window.__mesahaStatsResetMarkerV139&&window.__mesahaStatsResetMarkerV139.resetAtMs)||localReset();
  const keyOf=u=>{try{return firebaseUserKey(u&&u.name,u&&u.seflik);}catch{}return String(`${(u&&u.name)||""}__${(u&&u.seflik)||""}`).toLocaleLowerCase("tr-TR").replace(/[^a-z0-9ğüşöçıİĞÜŞÖÇ_-]+/gi,"_").replace(/^_+|_+$/g,"")||"bos";};

  async function readMarker(db){
    try{const real=db||(await ensureFirebaseReady()).db;const doc=await real.collection(usageColl()).doc(MARKER).get();if(doc.exists){const d=doc.data()||{};const r={resetAtMs:Number(d.resetAtMs||0),resetAt:d.resetAt||""};setLocalReset(r);return r;}}catch{}
    const r={resetAtMs:localReset(),resetAt:""};if(r.resetAtMs)setLocalReset(r);return r;
  }
  window.mesahaReadStatsResetMarkerV139=readMarker;

  function zeroUser(u){
    const out=Object.assign({},u||{});
    out.todayActiveMs=0;out.todayInputAdet=0;out.todayInputM3=0;out.todayRecordEntryCount=0;out.weekInputAdet=0;out.weekInputM3=0;out.lastUsageAt="";out.lastUsageMs=0;
    out.todayUsage=Object.assign({},out.todayUsage||{},{date:today(),activeMs:0,activeMinutes:0,inputAdet:0,inputM3:0,recordEntryCount:0,resetByAdmin:true});
    out.__statsZeroedV139=true;return out;
  }
  function sanitizeUsers(users,marker){
    const r=Number(marker&&marker.resetAtMs)||resetMs();if(!r)return Array.isArray(users)?users:[];
    return (Array.isArray(users)?users:[]).map(u=>{const tu=(u&&u.todayUsage)||{};const sm=Number(u&&(u.lastUsageMs||tu.updatedAtMs||tu.exportAtMs||tu.createdAtMs))||0;const has=n(u&&u.todayActiveMs)||n(u&&u.todayInputAdet)||n(u&&u.todayInputM3)||n(u&&u.weekInputAdet)||n(u&&u.weekInputM3)||n(tu.activeMs)||n(tu.inputAdet)||n(tu.inputM3);return has&&(!sm||sm<=r)?zeroUser(u):u;});
  }
  window.mesahaSanitizeUsersByResetV139=sanitizeUsers;

  const oldLoadUsage=typeof firebaseLoadUsageStatsV128==="function"?firebaseLoadUsageStatsV128:null;
  if(oldLoadUsage){firebaseLoadUsageStatsV128=async function(daysBack){const {db}=await ensureFirebaseReady();const marker=await readMarker(db);const days=Math.max(1,Number(daysBack||7));const start=new Date();start.setDate(start.getDate()-(days-1));const startIso=start.toISOString().slice(0,10);const snap=await db.collection(usageColl()).where("date",">=",startIso).get();const rows=[];snap.forEach(doc=>{if(doc.id===MARKER)return;const d=Object.assign({id:doc.id},doc.data()||{});if(String(d.type||"")==="statsResetMarker")return;const ms=genMs(d);if(marker.resetAtMs&&(!ms||ms<=marker.resetAtMs))return;rows.push(d);});return rows;};}
  const oldMerge=typeof usageMergeIntoUsersV128==="function"?usageMergeIntoUsersV128:null;
  if(oldMerge){usageMergeIntoUsersV128=function(users,rows){return sanitizeUsers(oldMerge(users,rows),window.__mesahaStatsResetMarkerV139||{resetAtMs:localReset()});};}
  const oldLoadUsers=typeof loadOnlineUsers==="function"?loadOnlineUsers:null;
  if(oldLoadUsers){loadOnlineUsers=async function(adminCode){const users=await oldLoadUsers(adminCode);let marker=window.__mesahaStatsResetMarkerV139||{resetAtMs:localReset()};try{marker=await readMarker();}catch{}return sanitizeUsers(users,marker);};}

  function status(u){const r=resetMs(),lm=Number(u&&u.lastUsageMs)||0,has=(n(u&&u.todayActiveMs)||n(u&&u.todayInputAdet)||n(u&&u.todayInputM3))>0;if(has&&(!r||lm>r))return{key:"today",label:"Bugün aktif"};try{if(!r&&typeof adminIsToday==="function"&&adminIsToday(u&&u.lastLogin))return{key:"today",label:"Bugün aktif"};if(typeof adminDaysSince==="function"&&adminDaysSince(u&&u.lastLogin)<=7)return{key:"warning",label:"Bu hafta aktif"};}catch{}return{key:"old",label:"Uzun süredir girmedi"};}
  function src(u){const s=(u&&(u.sourceLabel||u.source))||"";if(String(s).toLowerCase().includes("firebase"))return"Firebase";if(String(s).toLowerCase().includes("apps")||String(s).toLowerCase().includes("eski"))return"Eski";return"";}
  function device(u){return(u&&u.lastDeviceInfo&&(u.lastDeviceInfo.platform||u.lastDeviceInfo.userAgent))||(u&&u.lastDevice)||`${i(Number(u&&u.deviceCount)||0)} cihaz`;}
  function arg(v){return String(v||"").replace(/\\/g,"\\\\").replace(/'/g,"\\'");}
  function issues(u){try{const rows=Array.isArray(state.adminSupportTicketsV134)?state.adminSupportTicketsV134:[];const k=keyOf(u);return rows.filter(r=>String(r.userKey||keyOf(r))===String(k)&&String(r.status||"new")!=="done").length;}catch{return 0;}}
  function badges(u){const st=status(u);const parts=[`<span class="admin-badge-v134 ${st.key==="today"?"active":(st.key==="warning"?"week":"inactive")}">${esc(st.label)}</span>`];const bc=Number(u&&u.backupCount||0);parts.push(bc?`<span class="admin-badge-v134 ok">Yedek var</span>`:`<span class="admin-badge-v134 backup">Yedek yok</span>`);const is=issues(u);if(is)parts.push(`<span class="admin-badge-v134 issue">${i(is)} açık sorun</span>`);return`<div class="admin-user-badges-v134">${parts.join("")}</div>`;}
  adminFilteredUsers=function(){const list=Array.isArray(state&&state.adminOnlineUsers)?state.adminOnlineUsers.slice():[];return sanitizeUsers(list,window.__mesahaStatsResetMarkerV139||{resetAtMs:localReset()}).sort((a,b)=>(Number(b.lastUsageMs||b.lastLoginMs||0)-Number(a.lastUsageMs||a.lastLoginMs||0))||String(a.name||"").localeCompare(String(b.name||""),"tr"));};
  updateAdminTopSummary=function(){const users=sanitizeUsers(Array.isArray(state&&state.adminOnlineUsers)?state.adminOnlineUsers:[],window.__mesahaStatsResetMarkerV139||{resetAtMs:localReset()});if(state)state.adminOnlineUsers=users;const backups=(state&&state.adminBackups)||[];const todayUsers=users.filter(u=>n(u.todayActiveMs)||n(u.todayInputAdet)||n(u.todayInputM3)).length;const todayAdet=users.reduce((s,u)=>s+n(u.todayInputAdet),0);const todayM3=users.reduce((s,u)=>s+n(u.todayInputM3),0);const lastBackup=backups[0]&&backups[0].createdAt?backups[0].createdAt:"-";const setLabel=(el,label)=>{try{const x=el&&el.parentElement&&el.parentElement.querySelector("span");if(x)x.textContent=label;}catch{}};try{setLabel(els.adminTotalUsers,"Kullanıcı");setLabel(els.adminTodayUsers,"Bugün Aktif");setLabel(els.adminWeekUsers,"Bugün Adet");setLabel(els.adminTotalBackups,"Bugün m³");setLabel(els.adminLastBackup,"Son Yedek");if(els.adminTotalUsers)els.adminTotalUsers.textContent=users.length.toLocaleString("tr-TR");if(els.adminTodayUsers)els.adminTodayUsers.textContent=todayUsers.toLocaleString("tr-TR");if(els.adminWeekUsers)els.adminWeekUsers.textContent=todayAdet.toLocaleString("tr-TR");if(els.adminTotalBackups)els.adminTotalBackups.textContent=m3(todayM3).replace(" m³","");if(els.adminLastBackup)els.adminLastBackup.textContent=lastBackup;}catch{}};
  renderAdminUsers=function(){if(!els||!els.registeredUsersList)return;try{updateAdminTopSummary();}catch{}const list=adminFilteredUsers();window.__adminListV139=window.__adminListV134=window.__adminListV131=list;els.registeredUsersList.classList.add("admin-list-v131");if(!list.length){els.registeredUsersList.innerHTML=`<div class="empty-user-list">Kullanıcı bulunamadı.</div>`;return;}els.registeredUsersList.innerHTML=list.map((u,idx)=>{const st=status(u),is=issues(u),source=src(u),dev=device(u);return`
    <div class="admin-user-row-v131 status-${esc(st.key||"today")} ${is?"has-open-issue-v134":""}" data-admin-row-v131="${idx}">
      <div class="admin-user-main-v131"><b>${esc(u.name||"-")}</b><span>${esc(u.seflik||"-")} ${source?`• ${esc(source)}`:""}</span>${badges(u)}</div>
      <div class="admin-user-stats-v131"><span>Süre <b>${esc(dur(u.todayActiveMs))}</b></span><span>Adet <b>${esc(i(u.todayInputAdet))}</b></span><span>m³ <b>${esc(m3(u.todayInputM3))}</b></span></div>
      <button class="admin-detail-bubble-v131" type="button" onclick="adminToggleDetailV131(${idx})">Detay</button>
      <div class="admin-user-detail-panel-v131"><div class="admin-detail-grid-v131">
        <span>Durum <b>${esc(st.label||"-")}</b></span><span>İlk kayıt <b>${esc(u.firstLogin||u.createdAt||"Bilinmiyor")}</b></span><span>Son giriş <b>${esc(u.lastLogin||"-")}</b></span><span>Son aktif <b>${esc(u.lastUsageAt||"-")}</b></span><span>Son yedek <b>${esc(u.lastBackupAt||"-")}</b></span><span>Yedek sayısı <b>${i(u.backupCount)}</b></span><span>Açık sorun <b>${i(is)}</b></span><span>7 gün adet <b>${i(u.weekInputAdet)}</b></span><span>7 gün m³ <b>${esc(m3(u.weekInputM3))}</b></span><span>Sürüm <b>${esc(u.appVersion||u.fileVersion||"-")}</b></span><span>Cihaz <b>${esc(dev||"-")}</b></span>
      </div><div class="admin-detail-actions-v131"><button class="secondary" type="button" onclick="adminOpenUserBackups('${arg(u.name)}','${arg(u.seflik)}')">Yedekleri Gör</button>${is?`<button class="issue-v134" type="button" onclick="adminOpenUserReportsV134(${idx})">Sorunları Gör</button>`:""}<button class="danger-v134" type="button" onclick="adminDeleteUserV134(${idx})">Kullanıcıyı Sil</button><button class="ghost" type="button" onclick="adminToggleDetailV131(${idx})">Kapat</button></div></div>
    </div>`;}).join("");};

  async function deleteUsageDocs(db){let deleted=0;for(let round=0;round<30;round++){const snap=await db.collection(usageColl()).limit(450).get();const docs=[];snap.forEach(doc=>{if(doc.id!==MARKER)docs.push(doc);});if(!docs.length)break;const batch=db.batch();docs.forEach(doc=>batch.delete(doc.ref));await batch.commit();deleted+=docs.length;if(docs.length<450)break;}return deleted;}
  async function resetUserDocs(db,nowText,nowMs){const snap=await db.collection(usersColl()).get();const docs=[];snap.forEach(doc=>docs.push(doc));let count=0;for(let i0=0;i0<docs.length;i0+=430){const batch=db.batch();docs.slice(i0,i0+430).forEach(doc=>{batch.set(doc.ref,{todayUsage:{date:today(),activeMs:0,activeMinutes:0,inputAdet:0,inputM3:0,recordEntryCount:0,updatedAt:nowText,updatedAtMs:nowMs,resetByAdmin:true,resetAtMs:nowMs},lastUsageAt:"",lastUsageMs:0,lastExportSummary:null,statsResetAt:nowText,statsResetAtMs:nowMs},{merge:true});count++;});await batch.commit();}return count;}
  function clearLocal(resetAt){try{const raw=JSON.parse(localStorage.getItem(EXPORT_QUEUE)||"{}");const next={};if(raw&&typeof raw==="object")Object.keys(raw).forEach(k=>{const p=raw[k]&&(raw[k].payload||raw[k]);const ms=genMs(p||{});if(ms&&ms>resetAt)next[k]=raw[k];});localStorage.setItem(EXPORT_QUEUE,JSON.stringify(next));}catch{}try{localStorage.setItem(USAGE_LOCAL,"{}");localStorage.setItem("mesaha_usage_stats_v1","{}");localStorage.setItem("mesaha_stats_reset_at_v139",String(resetAt));localStorage.setItem("mesaha_stats_reset_at_v138",String(resetAt));}catch{}}
  function zeroState(){try{if(!state||!Array.isArray(state.adminOnlineUsers))return;state.adminOnlineUsers=state.adminOnlineUsers.map(u=>zeroUser(u));localStorage.setItem("mesaha_admin_users_cache_v1",JSON.stringify({time:new Date().toLocaleTimeString("tr-TR",{hour:"2-digit",minute:"2-digit"}),users:state.adminOnlineUsers}));}catch{}}
  window.adminResetStatsV139=async function(){if(!confirm("İstatistik ve admin kullanıcı listesindeki günlük deneme verileri sıfırlansın mı? Normal kayıtlar, yedekler, kullanıcılar ve sorun bildirimleri silinmez."))return;const word=prompt("Devam etmek için SIFIRLA yaz:");if(word!=="SIFIRLA"){toast("İşlem iptal edildi.");return;}try{if(typeof setCloudLoading==="function")setCloudLoading(true,"İstatistikler ve admin özetleri sıfırlanıyor...");}catch{}try{const {db}=await ensureFirebaseReady();const nowMs=Date.now();const nowText=typeof firebaseDateText==="function"?firebaseDateText():new Date().toLocaleString("tr-TR");const deleted=await deleteUsageDocs(db);const resetUsers=await resetUserDocs(db,nowText,nowMs);await db.collection(usageColl()).doc(MARKER).set({type:"statsResetMarker",resetAt:nowText,resetAtMs:nowMs,appVersion:BUILD_VERSION,fileVersion:FILE_VERSION,deletedDocs:deleted,resetUsers,updatedAt:nowText,updatedAtMs:nowMs},{merge:false});setLocalReset({resetAt:nowText,resetAtMs:nowMs});clearLocal(nowMs);zeroState();try{window.__mesahaStatsCacheV138={};window.__mesahaStatsCacheV139={};Object.keys(window.state||{}).filter(k=>/^adminStatsV13/.test(k)).forEach(k=>delete window.state[k]);}catch{}try{renderAdminUsers();updateAdminTopSummary();}catch{}toast(`İstatistik sıfırlandı. ${i(deleted)} eski özet ve ${i(resetUsers)} kullanıcı günlük özeti temizlendi.`);try{if(typeof adminRefreshStatsV132==="function")await adminRefreshStatsV132();}catch{}}catch(err){console.warn("v139 reset error",err);toast("İstatistik sıfırlanamadı. İnternet/Firebase bağlantısını kontrol et.");}finally{try{if(typeof setCloudLoading==="function")setCloudLoading(false);}catch{}}};
  window.adminResetStatsV138=window.adminResetStatsV137=window.adminResetStatsV136=window.adminResetStatsV139;
  const oldRefresh=typeof adminRefreshStatsV132==="function"?adminRefreshStatsV132:null;if(oldRefresh){adminRefreshStatsV132=async function(){try{setLocalReset(await readMarker());}catch{}return oldRefresh();};}
  const oldDevice=typeof currentDeviceInfoPayload==="function"?currentDeviceInfoPayload:null;try{currentDeviceInfoPayload=function(){const info=oldDevice?oldDevice():{};info.appVersion=BUILD_VERSION;info.fileVersion=FILE_VERSION;info.statsResetAdminListFix=true;info.updatedMs=Date.now();return info;};}catch{}
  window.MESAHA_BUILD_INFO=Object.assign({},window.MESAHA_BUILD_INFO||{},{fileVersion:FILE_VERSION,visibleVersion:BUILD_VERSION,statsResetAdminListFix:true,stableBuild:true});
  try{document.title="Mesaha App v139";const h1=document.querySelector(".brand h1");if(h1)h1.textContent=BUILD_VERSION;}catch{}
  setTimeout(()=>{readMarker().then(marker=>{if(marker&&marker.resetAtMs){try{state.adminOnlineUsers=sanitizeUsers(state.adminOnlineUsers||[],marker);renderAdminUsers();}catch{}}}).catch(()=>{});},1200);
})();
