-- Mesaha İO V5.48 — Google Auth kullanıcı eşleştirme ve erişim kapısı
-- Bu migration V5.47 migration sonrasında bir kez çalıştırılır.

create table if not exists public.mesaha_user_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  google_subject text,
  requested_name text,
  requested_seflik text,
  canonical_name text,
  canonical_seflik text,
  user_key text,
  bolme_no text,
  status text not null default 'pending' check (status in ('pending','approved','rejected','revoked')),
  reason text,
  requested_at timestamptz not null default now(),
  approved_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  last_seen_at timestamptz,
  last_ip text,
  device_id text,
  device_info jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mesaha_user_auth_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  event_type text not null,
  success boolean not null default true,
  ip_address text,
  device_id text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_mesaha_user_access_status on public.mesaha_user_access(status, updated_at desc);
create index if not exists idx_mesaha_user_access_email on public.mesaha_user_access(lower(email));
create index if not exists idx_mesaha_user_auth_events_user on public.mesaha_user_auth_events(user_id, created_at desc);
create index if not exists idx_mesaha_user_auth_events_created on public.mesaha_user_auth_events(created_at desc);
create unique index if not exists uq_mesaha_user_access_approved_user_key
  on public.mesaha_user_access(lower(user_key)) where status='approved' and user_key is not null and btrim(user_key)<>'';

create or replace function public.mesaha_user_access_touch_v548()
returns trigger language plpgsql as $$
begin
  new.updated_at=now();
  return new;
end $$;

drop trigger if exists mesaha_user_access_touch_v548 on public.mesaha_user_access;
create trigger mesaha_user_access_touch_v548
before update on public.mesaha_user_access
for each row execute function public.mesaha_user_access_touch_v548();

drop function if exists public.mesaha_is_approved_user_v548(uuid);
create or replace function public.mesaha_is_approved_user_v548()
returns boolean
language sql
stable
security definer
set search_path=public,auth
as $$
  select exists(
    select 1 from public.mesaha_user_access a
    where a.user_id=auth.uid() and a.status='approved'
  );
$$;

revoke all on function public.mesaha_is_approved_user_v548() from public, anon;
grant execute on function public.mesaha_is_approved_user_v548() to authenticated, service_role;

alter table public.mesaha_user_access enable row level security;
alter table public.mesaha_user_auth_events enable row level security;
revoke all on table public.mesaha_user_access from anon, authenticated;
revoke all on table public.mesaha_user_auth_events from anon, authenticated;
grant all on table public.mesaha_user_access to service_role;
grant all on table public.mesaha_user_auth_events to service_role;
grant usage, select on sequence public.mesaha_user_auth_events_id_seq to service_role;

-- Eski/yeni istemci doğrudan yedek REST çağrısı yaparsa Google + admin onayı zorunlu olsun.
-- RESTRICTIVE politikalar mevcut kullanıcı-kendi-verisi politikalarıyla AND olarak çalışır.
alter table public.mesaha_backup_slots enable row level security;
alter table public.mesaha_backup_chunks enable row level security;
revoke all on table public.mesaha_backup_slots from anon;
revoke all on table public.mesaha_backup_chunks from anon;
grant select, insert, update, delete on table public.mesaha_backup_slots to authenticated;
grant select, insert, update, delete on table public.mesaha_backup_chunks to authenticated;

-- Paket eski bir veritabanına da kurulabilsin: kullanıcı-kendi-satırı temel izinleri.
drop policy if exists "Mesaha V548 own backup slots" on public.mesaha_backup_slots;
create policy "Mesaha V548 own backup slots" on public.mesaha_backup_slots
  as permissive for all to authenticated
  using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists "Mesaha V548 own backup chunks" on public.mesaha_backup_chunks;
create policy "Mesaha V548 own backup chunks" on public.mesaha_backup_chunks
  as permissive for all to authenticated
  using (auth.uid()=user_id) with check (auth.uid()=user_id);

drop policy if exists "Mesaha V548 approved backup slots select" on public.mesaha_backup_slots;
create policy "Mesaha V548 approved backup slots select" on public.mesaha_backup_slots
  as restrictive for select to authenticated
  using (auth.uid()=user_id and public.mesaha_is_approved_user_v548());

drop policy if exists "Mesaha V548 approved backup slots insert" on public.mesaha_backup_slots;
create policy "Mesaha V548 approved backup slots insert" on public.mesaha_backup_slots
  as restrictive for insert to authenticated
  with check (auth.uid()=user_id and public.mesaha_is_approved_user_v548());

drop policy if exists "Mesaha V548 approved backup slots update" on public.mesaha_backup_slots;
create policy "Mesaha V548 approved backup slots update" on public.mesaha_backup_slots
  as restrictive for update to authenticated
  using (auth.uid()=user_id and public.mesaha_is_approved_user_v548())
  with check (auth.uid()=user_id and public.mesaha_is_approved_user_v548());

drop policy if exists "Mesaha V548 approved backup slots delete" on public.mesaha_backup_slots;
create policy "Mesaha V548 approved backup slots delete" on public.mesaha_backup_slots
  as restrictive for delete to authenticated
  using (auth.uid()=user_id and public.mesaha_is_approved_user_v548());

drop policy if exists "Mesaha V548 approved backup chunks select" on public.mesaha_backup_chunks;
create policy "Mesaha V548 approved backup chunks select" on public.mesaha_backup_chunks
  as restrictive for select to authenticated
  using (auth.uid()=user_id and public.mesaha_is_approved_user_v548());

drop policy if exists "Mesaha V548 approved backup chunks insert" on public.mesaha_backup_chunks;
create policy "Mesaha V548 approved backup chunks insert" on public.mesaha_backup_chunks
  as restrictive for insert to authenticated
  with check (auth.uid()=user_id and public.mesaha_is_approved_user_v548());

drop policy if exists "Mesaha V548 approved backup chunks update" on public.mesaha_backup_chunks;
create policy "Mesaha V548 approved backup chunks update" on public.mesaha_backup_chunks
  as restrictive for update to authenticated
  using (auth.uid()=user_id and public.mesaha_is_approved_user_v548())
  with check (auth.uid()=user_id and public.mesaha_is_approved_user_v548());

drop policy if exists "Mesaha V548 approved backup chunks delete" on public.mesaha_backup_chunks;
create policy "Mesaha V548 approved backup chunks delete" on public.mesaha_backup_chunks
  as restrictive for delete to authenticated
  using (auth.uid()=user_id and public.mesaha_is_approved_user_v548());

-- Eski anonim hesaplar yalnız Google kimliği bağlandıktan ve admin onayından sonra erişebilir.
-- Google sağlayıcısı ve anonimlik kontrolü Edge Function tarafında ayrıca doğrulanır.
