-- Mesaha İO V5.47 •Yakupp•
-- Admin Auth + başarısız giriş kilidi/logları + sunucu rate limit/idempotency.
-- Bu migration SQL Editor üzerinden bir kez çalıştırılır.

create table if not exists public.mesaha_admin_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  active boolean not null default true,
  session_version bigint not null default 1,
  last_login_at timestamptz,
  last_login_ip text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mesaha_admin_sessions (
  session_id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  ip_address text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists mesaha_admin_sessions_user_idx on public.mesaha_admin_sessions(user_id, revoked_at, last_seen_at desc);

create table if not exists public.mesaha_admin_audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  session_id text,
  ip_address text,
  event_type text not null,
  success boolean not null default false,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists mesaha_admin_audit_created_idx on public.mesaha_admin_audit_logs(created_at desc);
create index if not exists mesaha_admin_audit_email_idx on public.mesaha_admin_audit_logs(email, created_at desc);
create index if not exists mesaha_admin_audit_ip_idx on public.mesaha_admin_audit_logs(ip_address, created_at desc);

create table if not exists public.mesaha_rate_limits (
  bucket_key text primary key,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0,
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.mesaha_request_dedup (
  idempotency_key text primary key,
  user_id uuid,
  action text not null,
  response jsonb,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '1 day')
);
create index if not exists mesaha_request_dedup_exp_idx on public.mesaha_request_dedup(expires_at);

alter table public.mesaha_admin_accounts enable row level security;
alter table public.mesaha_admin_sessions enable row level security;
alter table public.mesaha_admin_audit_logs enable row level security;
alter table public.mesaha_rate_limits enable row level security;
alter table public.mesaha_request_dedup enable row level security;

revoke all on public.mesaha_admin_accounts from anon, authenticated;
revoke all on public.mesaha_admin_sessions from anon, authenticated;
revoke all on public.mesaha_admin_audit_logs from anon, authenticated;
revoke all on public.mesaha_rate_limits from anon, authenticated;
revoke all on public.mesaha_request_dedup from anon, authenticated;
grant all on public.mesaha_admin_accounts to service_role;
grant all on public.mesaha_admin_sessions to service_role;
grant all on public.mesaha_admin_audit_logs to service_role;
grant all on public.mesaha_rate_limits to service_role;
grant all on public.mesaha_request_dedup to service_role;

grant usage, select on sequence public.mesaha_admin_audit_logs_id_seq to service_role;

create or replace function public.mesaha_rate_limit_status(p_key text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.mesaha_rate_limits%rowtype;
  retry_seconds integer := 0;
begin
  select * into r from public.mesaha_rate_limits where bucket_key = p_key;
  if not found then
    return jsonb_build_object('allowed', true, 'count', 0, 'retry_after', 0);
  end if;
  if r.blocked_until is not null and r.blocked_until > now() then
    retry_seconds := greatest(1, ceil(extract(epoch from (r.blocked_until - now())))::integer);
    return jsonb_build_object('allowed', false, 'count', r.request_count, 'retry_after', retry_seconds, 'blocked_until', r.blocked_until);
  end if;
  return jsonb_build_object('allowed', true, 'count', r.request_count, 'retry_after', 0);
end;
$$;

create or replace function public.mesaha_take_rate_limit(
  p_key text,
  p_limit integer,
  p_window_seconds integer,
  p_block_seconds integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.mesaha_rate_limits%rowtype;
  now_ts timestamptz := now();
  retry_seconds integer := 0;
  next_count integer := 1;
begin
  insert into public.mesaha_rate_limits(bucket_key, window_started_at, request_count, blocked_until, updated_at)
  values (p_key, now_ts, 0, null, now_ts)
  on conflict (bucket_key) do nothing;

  select * into r from public.mesaha_rate_limits where bucket_key = p_key for update;

  if r.blocked_until is not null and r.blocked_until > now_ts then
    retry_seconds := greatest(1, ceil(extract(epoch from (r.blocked_until - now_ts)))::integer);
    return jsonb_build_object('allowed', false, 'count', r.request_count, 'retry_after', retry_seconds, 'blocked_until', r.blocked_until);
  end if;

  if r.window_started_at is null or r.window_started_at <= now_ts - make_interval(secs => greatest(1, p_window_seconds)) then
    r.window_started_at := now_ts;
    r.request_count := 0;
    r.blocked_until := null;
  end if;

  next_count := r.request_count + 1;
  if next_count > greatest(1, p_limit) then
    r.blocked_until := now_ts + make_interval(secs => greatest(1, p_block_seconds));
    update public.mesaha_rate_limits
      set request_count = next_count, blocked_until = r.blocked_until, window_started_at = r.window_started_at, updated_at = now_ts
      where bucket_key = p_key;
    retry_seconds := greatest(1, p_block_seconds);
    return jsonb_build_object('allowed', false, 'count', next_count, 'retry_after', retry_seconds, 'blocked_until', r.blocked_until);
  end if;

  update public.mesaha_rate_limits
    set request_count = next_count, blocked_until = null, window_started_at = r.window_started_at, updated_at = now_ts
    where bucket_key = p_key;
  return jsonb_build_object('allowed', true, 'count', next_count, 'retry_after', 0);
end;
$$;

create or replace function public.mesaha_reset_rate_limit(p_key text)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.mesaha_rate_limits where bucket_key = p_key;
$$;

create or replace function public.mesaha_grant_admin(p_email text, p_display_name text default null)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  uid uuid;
  normalized text := lower(trim(p_email));
begin
  select id into uid from auth.users where lower(email) = normalized limit 1;
  if uid is null then
    raise exception 'Supabase Auth kullanıcısı bulunamadı: %', normalized;
  end if;
  insert into public.mesaha_admin_accounts(user_id, email, display_name, active, updated_at)
  values(uid, normalized, nullif(trim(p_display_name), ''), true, now())
  on conflict (user_id) do update set email = excluded.email, display_name = excluded.display_name, active = true, updated_at = now();
  return uid;
end;
$$;

revoke all on function public.mesaha_rate_limit_status(text) from public, anon, authenticated;
revoke all on function public.mesaha_take_rate_limit(text, integer, integer, integer) from public, anon, authenticated;
revoke all on function public.mesaha_reset_rate_limit(text) from public, anon, authenticated;
revoke all on function public.mesaha_grant_admin(text, text) from public, anon, authenticated;
grant execute on function public.mesaha_rate_limit_status(text) to service_role;
grant execute on function public.mesaha_take_rate_limit(text, integer, integer, integer) to service_role;
grant execute on function public.mesaha_reset_rate_limit(text) to service_role;
grant execute on function public.mesaha_grant_admin(text, text) to service_role;

-- Auth kullanıcısını Dashboard > Authentication > Users bölümünde oluşturduktan sonra SQL Editor'da örnek:
-- select public.mesaha_grant_admin('yonetici@ornek.com', 'Yakup Düzgün');

-- V5.47: İstatistik/profil/log yazıları yalnız Edge Function service role üzerinden yapılır.
-- İstemci bu tabloları doğrudan doldurup spam üretemez.
revoke insert, update, delete on table public.mesaha_user_profiles from anon, authenticated;
revoke insert, update, delete on table public.mesaha_usage_current from anon, authenticated;
revoke insert, update, delete on table public.mesaha_usage_daily from anon, authenticated;
revoke insert, update, delete on table public.mesaha_log_current from anon, authenticated;
revoke insert, update, delete on table public.mesaha_security_events from anon, authenticated;

-- Yedek slot/chunk alanını sabitle: kullanıcı başına sınırsız yeni slot ve aşırı büyük chunk oluşturulamasın.
do $$
begin
  if not exists (select 1 from pg_constraint where conname='mesaha_backup_slots_allowed_slot_v547') then
    alter table public.mesaha_backup_slots add constraint mesaha_backup_slots_allowed_slot_v547
      check (slot_id in ('latest','slot_0','slot_1','slot_2','slot_3','slot_4')) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='mesaha_backup_slots_payload_size_v547') then
    alter table public.mesaha_backup_slots add constraint mesaha_backup_slots_payload_size_v547
      check (octet_length(coalesce(payload,'{}'::jsonb)::text) <= 2500000) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='mesaha_backup_chunks_index_v547') then
    alter table public.mesaha_backup_chunks add constraint mesaha_backup_chunks_index_v547
      check (chunk_index between 0 and 199) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='mesaha_backup_chunks_count_v547') then
    alter table public.mesaha_backup_chunks add constraint mesaha_backup_chunks_count_v547
      check (jsonb_typeof(records)='array' and jsonb_array_length(records) <= 180) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conname='mesaha_backup_chunks_size_v547') then
    alter table public.mesaha_backup_chunks add constraint mesaha_backup_chunks_size_v547
      check (octet_length(records::text) <= 750000) not valid;
  end if;
end $$;

-- Eski günlük istatistik RLS yazma politikalarını kaldır; select politikası korunur.
drop policy if exists "Mesaha usage daily insert own" on public.mesaha_usage_daily;
drop policy if exists "Mesaha usage daily update own" on public.mesaha_usage_daily;

-- Eski istemciler güncellenene kadar yedek tablolarına doğrudan erişim korunur;
-- ancak veritabanı seviyesinde kullanıcı başına yazma hızı sınırlandırılır.
create or replace function public.mesaha_backup_write_guard_v547()
returns trigger
language plpgsql
security definer
set search_path=public, auth
as $$
declare
  uid uuid := auth.uid();
  role_name text := coalesce(auth.role(), '');
  r jsonb;
  bucket text;
  allowed_limit integer;
begin
  if role_name = 'service_role' or uid is null then return new; end if;
  if tg_table_name = 'mesaha_backup_slots' then
    bucket := 'backup-slot-db:' || uid::text;
    allowed_limit := 30;
  else
    bucket := 'backup-chunk-db:' || uid::text;
    allowed_limit := 900;
  end if;
  r := public.mesaha_take_rate_limit(bucket, allowed_limit, 3600, 1800);
  if coalesce((r->>'allowed')::boolean, false) is not true then
    raise exception 'Yedek yazma sınırı aşıldı. Daha sonra tekrar deneyin.' using errcode='P0001';
  end if;
  return new;
end;
$$;
revoke all on function public.mesaha_backup_write_guard_v547() from public, anon, authenticated;
grant execute on function public.mesaha_backup_write_guard_v547() to service_role;

drop trigger if exists mesaha_backup_slots_rate_v547 on public.mesaha_backup_slots;
create trigger mesaha_backup_slots_rate_v547
before insert or update on public.mesaha_backup_slots
for each row execute function public.mesaha_backup_write_guard_v547();

drop trigger if exists mesaha_backup_chunks_rate_v547 on public.mesaha_backup_chunks;
create trigger mesaha_backup_chunks_rate_v547
before insert or update on public.mesaha_backup_chunks
for each row execute function public.mesaha_backup_write_guard_v547();

-- Audit tablosu saldırı altında sınırsız büyümesin.
create or replace function public.mesaha_security_cleanup_v547()
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  d1 integer:=0; d2 integer:=0; d3 integer:=0; d4 integer:=0;
begin
  delete from public.mesaha_request_dedup where expires_at < now(); get diagnostics d1=row_count;
  delete from public.mesaha_rate_limits where updated_at < now()-interval '7 days'; get diagnostics d2=row_count;
  delete from public.mesaha_admin_sessions where revoked_at is not null and revoked_at < now()-interval '30 days'; get diagnostics d3=row_count;
  delete from public.mesaha_admin_audit_logs where created_at < now()-interval '180 days'; get diagnostics d4=row_count;
  return jsonb_build_object('dedup',d1,'rate',d2,'sessions',d3,'audit',d4);
end;
$$;
revoke all on function public.mesaha_security_cleanup_v547() from public, anon, authenticated;
grant execute on function public.mesaha_security_cleanup_v547() to service_role;
