(function(){'use strict';
function r(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch(e){return f}}
function w(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){return false}}
function c(v){return String(v==null?'':v).trim()}
function sk(v){return c(v).toLocaleLowerCase('tr-TR').replace(/ç/g,'c').replace(/ğ/g,'g').replace(/ı/g,'i').replace(/ö/g,'o').replace(/ş/g,'s').replace(/ü/g,'u').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
function valid(){var s=r('mesaha_supabase_v500_session',{}),b=r('mesaha_supabase_v569_session_backup',{}),a=r('mesaha_google_access_v548',{}),t=r('mesaha_terminal_local_mode_v556',{})||r('mesaha_terminal_local_mode_v557',{});return !!(s.access_token||b.access_token||a.status==='approved'||t&&t.active)}
async function rootWorker(){try{var regs=await navigator.serviceWorker.getRegistrations();for(var reg of regs){if(String(reg.scope).includes('/test/mesaha/')||String(reg.scope).includes('/test/istif/'))await reg.unregister()}return await navigator.serviceWorker.register('../service-worker.js?v=6',{scope:'../',updateViaCache:'none'})}catch(e){}}
function add(){if(document.getElementById('suiteHomeButtonV2'))return;var b=document.createElement('button');b.id='suiteHomeButtonV2';b.className='suite-home-button';b.type='button';b.textContent='⌂ Suite';b.onclick=function(){location.href='../'};document.body.appendChild(b)}
function folders(){var a=r('mesaha_suite_folder_cache_v4',[]);return Array.isArray(a)?a.filter(function(x){return x&&!x.deleted}):[]}
function active(){var a=r('mesaha_active_seflik_folder_v564',{}),fs=folders();return fs.find(function(f){return c(f.seflik_key||f.seflikKey)===c(a.seflik_key||a.seflikKey)})||fs.find(function(f){return c(f.seflik)===c(a.seflik)})||fs[0]||null}
function readyDivisions(f){if(!f)return[];var m=r('mesaha_suite_divisions_v4',{}),ready=r('mesaha_suite_division_ready_v4',{}),key=c(f.seflik_key||f.seflikKey)||sk(f.seflik),list=Array.isArray(m[key])?m[key]:[];return list.filter(function(d){var no=c(d.bolme_no||d.bolmeNo||d.bolme);return no&&!d.deleted&&(d.offline_ready||ready[key+'::'+no])}).map(function(d){return c(d.bolme_no||d.bolmeNo||d.bolme)}).sort(function(a,b){return a.localeCompare(b,'tr',{numeric:true})})}
function setActive(f){if(!f)return;var sf=c(f.seflik),key=c(f.seflik_key||f.seflikKey)||sk(sf);w('mesaha_active_seflik_folder_v564',{seflik:sf,seflik_key:key,role:f.role||'',creator:!!f.is_creator,updatedAt:new Date().toISOString()});var p=r('mesaha_panel_user_v316',{}),s=r('cam_mesaha_ayarlar_v1',{});p.seflik=sf;p.activeSeflik=sf;s.seflik=sf;w('mesaha_panel_user_v316',p);w('cam_mesaha_ayarlar_v1',s)}
function setBolme(no){var p=r('mesaha_panel_user_v316',{}),s=r('cam_mesaha_ayarlar_v1',{});p.bolmeNo=no;s.bolmeNo=no;w('mesaha_panel_user_v316',p);w('cam_mesaha_ayarlar_v1',s);try{localStorage.setItem('mesaha_seflik_folder_last_bolme_v529',no)}catch(e){}var input=document.getElementById('bolmeNo');if(input){input.value=no;input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}))}}
function select(id,values,current,onchange,empty){var el=document.getElementById(id);if(!el){el=document.createElement('select');el.id=id;el.className='suite-managed-select-v5'}el.innerHTML=(values.length?values:[empty||'Seçenek yok']).map(function(v){var val=typeof v==='string'?v:v.value,label=typeof v==='string'?v:v.label;return '<option value="'+String(val).replace(/"/g,'&quot;')+'" '+(c(val)===c(current)?'selected':'')+'>'+label+'</option>'}).join('');el.disabled=!values.length;el.onchange=onchange;return el}
function syncSelectors(){var f=active();if(f)setActive(f);var seflikInput=document.getElementById('seflik'),bolmeInput=document.getElementById('bolmeNo');if(seflikInput){seflikInput.readOnly=true;seflikInput.style.display='none';var fs=folders(),sel=select('suiteSeflikSelectV6',fs.map(function(x,i){return{value:i,label:c(x.seflik)+(x.is_creator?' • kurucu':' • üye')}}),Math.max(0,fs.indexOf(f)),function(){var nf=fs[Number(this.value)];setActive(nf);syncSelectors();try{window.dispatchEvent(new Event('mesaha:seflik-folder-active-changed'))}catch(e){}});if(!sel.parentNode)seflikInput.parentNode.appendChild(sel)}if(bolmeInput){bolmeInput.readOnly=true;bolmeInput.style.display='none';var ds=readyDivisions(f),st=r('cam_mesaha_ayarlar_v1',{}),cur=c(st.bolmeNo||r('mesaha_panel_user_v316',{}).bolmeNo),bs=select('suiteBolmeSelectV6',ds,cur,function(){setBolme(this.value)},'Önce Suite’ten offline bölme indirin');if(!bs.parentNode)bolmeInput.parentNode.appendChild(bs);if(ds.length&&!ds.includes(cur))setBolme(ds[0])}['panelSeflikV316','panelBolmeV316'].forEach(function(id){var x=document.getElementById(id);if(x){x.readOnly=true;x.title='Bu alan Mesaha Suite üzerinden yönetilir.'}})}
function note(){var host=document.querySelector('#seflikFolderView .seflik-folder-control');if(host&&!document.getElementById('suiteManagedNoteV6')){var n=document.createElement('div');n.id='suiteManagedNoteV6';n.className='suite-managed-note-v5';n.textContent='Şeflik, ormancı ve bölme düzenlemeleri Mesaha Suite ana menüsünden yapılır. Bu ekranda yalnızca seçim, senkronizasyon ve mesahaya devam işlemleri bulunur.';host.insertBefore(n,host.firstChild)}}
function block(ev){var t=ev.target&&ev.target.closest&&ev.target.closest('#seflikFolderCreateV629,[data-seflik-delete],#seflikCreateBtnV664,#seflikDeleteBtnV664,#seflikUserSearchBtnV664,[data-add-user-v564],[data-remove-member-v566]');if(!t)return;ev.preventDefault();ev.stopPropagation();ev.stopImmediatePropagation();alert('Bu düzenleme Mesaha Suite ana menüsünden yapılır.');return false}
if(!valid()){location.replace('../');return}window.MESAHA_SUITE_MODE=true;rootWorker();setActive(active());if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){add();syncSelectors();note()},{once:true});else{add();syncSelectors();note()}document.addEventListener('click',block,true);window.addEventListener('mesaha-suite:shared-data-updated',syncSelectors);window.addEventListener('storage',syncSelectors);var mo=new MutationObserver(function(){syncSelectors();note()});document.addEventListener('DOMContentLoaded',function(){mo.observe(document.body,{childList:true,subtree:true})},{once:true});
})();