(function(){'use strict';
const read=(k,f)=>{try{const x=JSON.parse(localStorage.getItem(k)||'null');return x==null?f:x}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}},clean=v=>String(v==null?'':v).trim(),fold=v=>clean(v).toLocaleLowerCase('tr-TR').replace(/ç/g,'c').replace(/ğ/g,'g').replace(/ı/g,'i').replace(/ö/g,'o').replace(/ş/g,'s').replace(/ü/g,'u').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
function valid(){const s=read('mesaha_supabase_v500_session',{}),b=read('mesaha_supabase_v569_session_backup',{}),a=read('mesaha_google_access_v548',{}),t=read('mesaha_terminal_local_mode_v556',{})||read('mesaha_terminal_local_mode_v557',{});return !!(s.access_token||b.access_token||a.status==='approved'||t&&t.active)}
function addCss(){if(document.getElementById('suiteCentralCssV7'))return;const x=document.createElement('style');x.id='suiteCentralCssV7';x.textContent=`#startup{display:none!important}.suite-home-button{position:fixed!important;right:max(12px,env(safe-area-inset-right))!important;bottom:max(12px,env(safe-area-inset-bottom))!important;z-index:2147482000!important;border:0!important;border-radius:15px!important;padding:12px 15px!important;background:#fff!important;color:#174a32!important;box-shadow:0 10px 28px #0002!important;font-weight:800!important}.suite-managed-select-v7{width:100%;min-height:48px;border:1px solid #d7e4dc;border-radius:14px;padding:0 12px;background:#fff;color:#173d2d;font:700 14px system-ui}.suite-managed-note-v7{margin:8px 0 12px;padding:11px 13px;border-radius:13px;background:#edf7f0;color:#28543d;font:600 12px/1.45 system-ui}.suite-central-hidden-v7{display:none!important}`;document.head.appendChild(x)}
function home(){if(document.getElementById('suiteHomeButtonV7'))return;const b=document.createElement('button');b.id='suiteHomeButtonV7';b.className='suite-home-button';b.type='button';b.textContent='⌂ Suite';b.onclick=()=>location.href='../';document.body.appendChild(b)}
function folders(){const x=read('mesaha_suite_folder_cache_v4',[]);return Array.isArray(x)?x.filter(f=>f&&!f.deleted):[]}
function active(){const a=read('mesaha_active_seflik_folder_v564',{}),fs=folders();return fs.find(f=>clean(f.seflik_key||f.seflikKey)===clean(a.seflik_key||a.seflikKey))||fs.find(f=>clean(f.seflik)===clean(a.seflik))||fs[0]||null}
function readyDivisions(f){if(!f)return[];const all=read('mesaha_suite_divisions_v4',{}),ready=read('mesaha_suite_division_ready_v4',{}),key=clean(f.seflik_key||f.seflikKey)||fold(f.seflik),list=Array.isArray(all[key])?all[key]:[];return list.filter(d=>{const no=clean(d.bolme_no||d.bolmeNo||d.bolme);return no&&!d.deleted&&(d.offline_ready||ready[key+'::'+no])}).map(d=>clean(d.bolme_no||d.bolmeNo||d.bolme)).sort((a,b)=>a.localeCompare(b,'tr',{numeric:true}))}
function setActive(f){if(!f)return;const sf=clean(f.seflik),key=clean(f.seflik_key||f.seflikKey)||fold(sf);write('mesaha_active_seflik_folder_v564',{seflik:sf,seflik_key:key,role:f.role||'',creator:!!f.is_creator,updatedAt:new Date().toISOString()});const p=read('mesaha_panel_user_v316',{}),s=read('cam_mesaha_ayarlar_v1',{});p.seflik=sf;p.activeSeflik=sf;s.seflik=sf;write('mesaha_panel_user_v316',p);write('cam_mesaha_ayarlar_v1',s)}
function setBolme(no){const p=read('mesaha_panel_user_v316',{}),s=read('cam_mesaha_ayarlar_v1',{});p.bolmeNo=no;s.bolmeNo=no;write('mesaha_panel_user_v316',p);write('cam_mesaha_ayarlar_v1',s);try{localStorage.setItem('mesaha_seflik_folder_last_bolme_v529',no)}catch{}const i=document.getElementById('bolmeNo');if(i){i.value=no;i.dispatchEvent(new Event('input',{bubbles:true}));i.dispatchEvent(new Event('change',{bubbles:true}))}}
function select(id,rows,current,change,empty){let el=document.getElementById(id);if(!el){el=document.createElement('select');el.id=id;el.className='suite-managed-select-v7'}el.innerHTML=(rows.length?rows:[{value:'',label:empty||'Seçenek yok'}]).map(x=>{const v=typeof x==='string'?x:x.value,l=typeof x==='string'?x:x.label;return `<option value="${String(v).replace(/"/g,'&quot;')}" ${clean(v)===clean(current)?'selected':''}>${l}</option>`}).join('');el.disabled=!rows.length;el.onchange=change;return el}
const hideSelectors=['#seflikFolderCreateV629','[data-seflik-delete]','#seflikCreateBtnV664','#seflikDeleteBtnV664','#seflikUserSearchBtnV664','[data-add-user-v564]','[data-remove-member-v566]','#panelSyncV316','#cloudBackupBtnV316','#cloudRestoreBtnV316','#panelSeflikV316','#panelBolmeV316','#seflikFolderSyncV528','#seflikFolderSendV528','#seflikSendFromRecordsV529','#seflikSendOverlayV529','[data-action="refresh-shared"]','[data-action="connect-drive"]','[data-action="disconnect-drive"]'];
function hideManagement(){for(const sel of hideSelectors)document.querySelectorAll(sel).forEach(el=>el.classList.add('suite-central-hidden-v7'));document.querySelectorAll('button,a').forEach(el=>{const t=clean(el.textContent).toLocaleLowerCase('tr-TR');if(/şeflik oluştur|şefliği sil|şeflik sil|ormancı ekle|ormancı çıkar|bölme oluştur|bölme sil|buluta yedekle|buluttan geri yükle|güncelleme kontrol/.test(t))el.classList.add('suite-central-hidden-v7')})}
function selectors(){const f=active();if(f)setActive(f);const si=document.getElementById('seflik'),bi=document.getElementById('bolmeNo');if(si&&si.parentNode){si.readOnly=true;si.style.display='none';const fs=folders(),cur=Math.max(0,fs.indexOf(f)),sel=select('suiteSeflikSelectV7',fs.map((x,i)=>({value:i,label:clean(x.seflik)+(x.is_creator?' • kurucu':' • üye')})),cur,function(){setActive(fs[Number(this.value)]);schedule();try{window.dispatchEvent(new Event('mesaha:seflik-folder-active-changed'))}catch{}},'Suite’ten şeflik oluşturun');if(!sel.parentNode)si.parentNode.appendChild(sel)}if(bi&&bi.parentNode){bi.readOnly=true;bi.style.display='none';const ds=readyDivisions(f),st=read('cam_mesaha_ayarlar_v1',{}),cur=clean(st.bolmeNo||read('mesaha_panel_user_v316',{}).bolmeNo),sel=select('suiteBolmeSelectV7',ds,cur,function(){setBolme(this.value)},'Suite’ten offline bölme oluşturun');if(!sel.parentNode)bi.parentNode.appendChild(sel);if(ds.length&&!ds.includes(cur))setBolme(ds[0])}}
function note(){const host=document.querySelector('#seflikFolderView .seflik-folder-control')||document.querySelector('#seflikFolderView');if(host&&!document.getElementById('suiteManagedNoteV7')){const n=document.createElement('div');n.id='suiteManagedNoteV7';n.className='suite-managed-note-v7';n.textContent='Şeflik, ormancı, bölme, Drive, yedek ve sunucu senkronizasyonu yalnızca Mesaha Suite ana menüsünden yönetilir. Burada sadece kayıt ve seçim işlemleri bulunur.';host.insertBefore(n,host.firstChild)}}
let timer=0;function schedule(){clearTimeout(timer);timer=setTimeout(()=>{hideManagement();selectors();note();window.MesahaSuiteSyncV7&&window.MesahaSuiteSyncV7.updateButton()},120)}
function block(e){const t=e.target.closest&&e.target.closest(hideSelectors.join(','));if(!t)return;e.preventDefault();e.stopImmediatePropagation();location.href='../'}
if(!valid()){location.replace('../');return}window.MESAHA_SUITE_MODE=true;addCss();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{home();schedule()},{once:true});else{home();schedule()}document.addEventListener('click',block,true);window.addEventListener('storage',schedule);window.addEventListener('mesaha-suite:shared-data-updated',schedule);window.addEventListener('mesaha-suite:sync-complete',schedule);document.addEventListener('mesaha:records-saved',()=>window.MesahaSuiteSyncV7&&window.MesahaSuiteSyncV7.markDirty('mesaha'));const watchSel=hideSelectors.join(',')+',#seflik,#bolmeNo,button,a';const mo=new MutationObserver(ms=>{for(const m of ms){for(const n of m.addedNodes){if(n.nodeType===1&&(n.matches&&n.matches(watchSel)||n.querySelector&&n.querySelector(watchSel))){schedule();return}}}});document.addEventListener('DOMContentLoaded',()=>mo.observe(document.body,{childList:true,subtree:true}),{once:true});setTimeout(schedule,350);setTimeout(schedule,1200);
})();
