'use strict';
const APP_VERSION='0.1.0';
const MAX_PHOTO_BYTES=1024*1024;
const DB_NAME='mesaha-istif-prototype';
const DB_VERSION=1;
const TYPE_ORDER=['İbreli Kabuklu Kağıtlık Odun','İbreli Lif Yonga Odun','İbreli Yakacak Odun','İbreli Sırık'];
const DEFAULT_SETTINGS={seflik:'Yaylacık Şefliği',ormanci:'Mehmet Yılmaz',driveClientId:'',driveFolderId:'',driveCreatedFolderId:'',serverEndpoint:'',photoMaxBytes:MAX_PHOTO_BYTES};
const state={view:'home',records:[],settings:{...DEFAULT_SETTINGS},draft:null,selectedPhotos:[],selectedRecordIds:new Set(),documentTab:'documents',cameraStream:null,facingMode:'environment',syncing:false};
const app=document.getElementById('app');
const picker=document.getElementById('photoPicker');
const cameraModal=document.getElementById('cameraModal');
const cameraVideo=document.getElementById('cameraVideo');
const dialogModal=document.getElementById('dialogModal');
const dialogContent=document.getElementById('dialogContent');
let dbPromise=null;

const icons={home:'⌂',logs:'▱',doc:'▤',gear:'⚙',plus:'＋',camera:'◉',calendar:'▦',person:'♙',forest:'♜',pin:'⌖',cube:'◇',barcode:'▥',cloud:'☁',filter:'▽',photo:'▣',sync:'↥',trash:'⌫',check:'✓',info:'ⓘ',back:'‹',bell:'♧',eye:'◉',share:'⌯'};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const trDate=s=>{if(!s)return'';const [y,m,d]=s.split('-');return `${d}.${m}.${y}`};
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;

function openDB(){
  if(dbPromise)return dbPromise;
  dbPromise=new Promise((resolve,reject)=>{
    const req=indexedDB.open(DB_NAME,DB_VERSION);
    req.onupgradeneeded=()=>{
      const db=req.result;
      if(!db.objectStoreNames.contains('records'))db.createObjectStore('records',{keyPath:'id'});
      if(!db.objectStoreNames.contains('settings'))db.createObjectStore('settings',{keyPath:'key'});
    };
    req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);
  });
  return dbPromise;
}
async function idbGetAll(store){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function idbPut(store,value){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function idbDelete(store,key){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function saveSettings(){await idbPut('settings',{key:'app',value:state.settings})}
async function loadData(){
  state.records=await idbGetAll('records');
  const rows=await idbGetAll('settings');const saved=rows.find(x=>x.key==='app');if(saved)state.settings={...DEFAULT_SETTINGS,...saved.value};
  if(!state.records.length){for(const r of demoRecords())await idbPut('records',r);state.records=await idbGetAll('records')}
}
function demoRecords(){
  const base={seflik:'Yaylacık Şefliği',ormanci:'Mehmet Yılmaz',coordinates:'41.3892, 33.7834',mevki:'Çamlık Mevkii',description:'Örnek prototip kaydı',barcode:'',photos:[],createdAt:new Date().toISOString()};
  return [
    {...base,id:uid(),date:'2026-07-12',bolme:'124',istifNo:'İ-03',type:'İbreli Kabuklu Kağıtlık Odun',ster:'45,60',syncStatus:'local',photoCount:4},
    {...base,id:uid(),date:'2026-07-12',bolme:'124',istifNo:'İ-08',type:'İbreli Lif Yonga Odun',ster:'78,40',syncStatus:'local',photoCount:4},
    {...base,id:uid(),date:'2026-07-12',bolme:'124',istifNo:'İ-09',type:'İbreli Yakacak Odun',ster:'32,15',syncStatus:'local',photoCount:4},
    {...base,id:uid(),date:'2026-07-10',bolme:'125',istifNo:'İ-02',type:'İbreli Sırık 4 Boy',ster:'60,00',coordinates:'',syncStatus:'pending',photoCount:2}
  ];
}
function logo(){return `<img class="brand-logo" src="../assets/icon-192.png" onerror="this.onerror=null;this.src='./assets/mesaha-fallback.svg'" alt="Mesaha İO">`}
function head(title,subtitle,{back=false,action=''}={}){return `<header class="page-head ${back?'compact':''}">${back?`<button class="back-btn" data-action="back">${icons.back}</button>`:logo()}<div class="title-wrap"><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div>${action?`<div class="head-action">${action}</div>`:''}</header>`}
function nav(active){return `<nav class="bottom-nav">${[['home',icons.home,'Ana Sayfa'],['records',icons.logs,'İstifler'],['documents',icons.doc,'Evraklar'],['settings',icons.gear,'Ayarlar']].map(([v,i,l])=>`<button class="nav-btn ${active===v?'active':''}" data-view="${v}"><span class="nicon">${i}</span><span>${l}</span></button>`).join('')}</nav>`}
function metric(icon,n,label){return `<div class="metric card"><div class="metric-icon">${icon}</div><b>${n}</b><span>${label}</span></div>`}
function setView(v){stopCamera();state.view=v;render();scrollTo({top:0,behavior:'smooth'})}
function render(){
  const views={home:renderHome,new:renderNew,records:renderRecords,documents:renderDocuments,templates:renderTemplates,settings:renderSettings,photos:renderPhotos};
  app.innerHTML=`<main class="view">${(views[state.view]||renderHome)()}</main>${nav(state.view==='new'?'records':state.view==='templates'?'documents':state.view)}`;
  bindDynamic();
}
function counts(){return {records:state.records.length,photos:state.records.reduce((a,r)=>a+(r.photos?.length||r.photoCount||0),0),pending:state.records.filter(r=>r.syncStatus!=='synced').length}}
function renderHome(){const c=counts();return `${head('İstif Alma','Mesaha İO modülü',{action:`<button class="icon-btn" aria-label="Bildirimler">${icons.bell}</button>`})}
  <section class="sync-banner card"><span class="round-icon" style="width:38px;height:38px">${icons.sync}</span><div class="sync-copy"><strong>Offline kullanılabilir</strong> • ${c.pending} kayıt senkron bekliyor</div><button class="btn primary small" data-action="sync">Senkronize Et</button></section>
  <section class="metrics">${metric(icons.logs,c.records,'Toplam İstif')}${metric(icons.calendar,state.records.filter(r=>r.date===today()).length||7,'Bugün')}${metric(icons.camera,c.photos,'Fotoğraf')}${metric(icons.doc,3,'Evrak')}</section>
  <section class="select-panel card"><button class="select-row" data-view="settings"><span class="round-icon">${icons.forest}</span><span class="row-copy"><small>Şeflik</small><strong>${esc(state.settings.seflik)}</strong></span><span class="chev">›</span></button><button class="select-row" data-view="settings"><span class="round-icon">${icons.person}</span><span class="row-copy"><small>Ormancı</small><strong>${esc(state.settings.ormanci)}</strong></span><span class="chev">›</span></button></section>
  <div class="section-title"><h2>İşlemler</h2></div><section class="actions-grid"><button class="action-card" data-view="new"><span class="aicon">${icons.plus}</span>Yeni İstif</button><button class="action-card" data-view="records"><span class="aicon">${icons.logs}</span>İstifler</button><button class="action-card" data-view="documents"><span class="aicon">${icons.doc}</span>Evrak Oluştur</button><button class="action-card" data-view="photos"><span class="aicon">${icons.camera}</span>Fotoğraflar</button></section>
  <div class="section-title"><h2>Bekleyenler</h2></div><section class="pending-card card"><div class="pending-row"><i class="dot"></i>Yerelde kayıtlı<b>${state.records.filter(r=>r.syncStatus==='local').length}</b></div><div class="pending-row"><i class="dot wait"></i>Drive yükleme bekliyor<b>${state.records.reduce((a,r)=>a+(r.syncStatus!=='synced'?(r.photos?.length||r.photoCount||0):0),0)} fotoğraf</b></div><div class="pending-row"><i class="dot bad"></i>Sunucu kaydı bekliyor<b>${state.records.filter(r=>r.syncStatus==='drive_synced').length||state.records.filter(r=>r.syncStatus!=='synced').length}</b></div></section>`}
function freshDraft(){return {id:uid(),seflik:state.settings.seflik,ormanci:state.settings.ormanci,date:today(),bolme:'',istifNo:'',type:'İbreli Kabuklu Kağıtlık Odun',ster:'',coordinates:'',mevki:'',description:'',barcode:'',photos:[],createdAt:new Date().toISOString(),syncStatus:'local'}}
function ensureDraft(){if(!state.draft)state.draft=freshDraft();return state.draft}
function fieldRow(icon,label,name,value,type='text',options=[]){const control=type==='select'?`<select name="${name}">${options.map(o=>`<option ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${name}" placeholder="İsteğe bağlı">${esc(value)}</textarea>`:`<input name="${name}" value="${esc(value)}" type="${type}" ${type==='number'?'inputmode="decimal" step="0.01"':''}>`;return `<div class="field-row"><span class="field-icon">${icon}</span><div class="field-main"><label>${label}</label>${control}</div><span class="chev">›</span></div>`}
function renderNew(){const d=ensureDraft();return `${head('Yeni İstif','Şeflik, ormancı ve istif bilgilerini gir',{back:true})}<form id="stackForm">
  <section class="form-card card">${fieldRow(icons.forest,'Şeflik','seflik',d.seflik)}${fieldRow(icons.person,'Ormancı','ormanci',d.ormanci)}${fieldRow(icons.calendar,'Tarih','date',d.date,'date')}${fieldRow('▦','Bölme','bolme',d.bolme)}${fieldRow(icons.logs,'İstif No','istifNo',d.istifNo)}${fieldRow('♠','Odun Türü','type',d.type,'select',['İbreli Kabuklu Kağıtlık Odun','İbreli Lif Yonga Odun','İbreli Yakacak Odun','İbreli Sırık 2 Boy','İbreli Sırık 3 Boy','İbreli Sırık 4 Boy','İbreli Sırık 5 Boy'])}${fieldRow(icons.cube,'Ster Sayısı','ster',d.ster,'number')}</section>
  <div class="photo-head"><h2>Koordinat</h2></div><section class="coord-grid card"><input name="coordinates" value="${esc(d.coordinates)}" placeholder="Enlem, boylam"><button class="btn small" type="button" data-action="geo">${icons.pin} Mevcut Konumu Ekle</button></section>
  <div class="photo-head"><h2>Resim Ekle</h2><span class="photo-counter">${state.selectedPhotos.length}/4</span></div><section class="photo-grid">${[0,1,2,3].map(i=>photoSlot(i)).join('')}</section>
  <section class="form-card card" style="margin-top:12px">${fieldRow(icons.pin,'Mevki','mevki',d.mevki)}${fieldRow(icons.doc,'Açıklama','description',d.description,'textarea')}${fieldRow(icons.barcode,'Barkod No','barcode',d.barcode)}</section>
  <div class="info-note"><b>${icons.info}</b><span>Uygulama içi kamera ile çekilen fotoğraflar cihaz galerisinde görünmez. Fotoğraflar yaklaşık 1 MB altında sıkıştırılarak yalnızca uygulama içinde saklanır.</span></div>
  <div class="stack-actions"><button class="btn primary wide" type="submit">▣ Kaydet</button><button class="btn wide" type="button" data-action="save-draft">${icons.doc} Taslağa Ekle</button></div></form>`}
function photoSlot(i){const p=state.selectedPhotos[i];if(p){const url=URL.createObjectURL(p.blob);return `<div class="photo-slot"><img src="${url}" alt="Fotoğraf ${i+1}"><button class="remove-photo" type="button" data-remove-photo="${i}" aria-label="Fotoğrafı sil">${icons.trash}</button></div>`}return `<button class="photo-slot addable" type="button" data-add-photo><span class="photo-placeholder"><b>${icons.camera}</b>Fotoğraf ${i+1}</span></button>`}
function sortedRecords(list=state.records){return [...list].sort((a,b)=>{const ai=TYPE_ORDER.findIndex(t=>a.type.startsWith(t));const bi=TYPE_ORDER.findIndex(t=>b.type.startsWith(t));return (ai<0?99:ai)-(bi<0?99:bi)||String(a.istifNo).localeCompare(String(b.istifNo),'tr')})}
function renderRecords(){const bolmes=[...new Set(state.records.map(r=>r.bolme))];return `${head('İstifler','Tarih, bölme ve istife göre filtrele',{back:true,action:`<button class="icon-btn">${icons.filter}</button>`})}<section class="filter-grid"><div class="filter-box"><label>Tarih Seç</label><input id="filterDate" type="date" value=""></div><div class="filter-box"><label>Bölme Seç</label><select id="filterBolme"><option value="">Tümü</option>${bolmes.map(x=>`<option>${esc(x)}</option>`).join('')}</select></div><div class="filter-box"><label>İstif Seç</label><select id="filterType"><option value="">Tümü</option>${TYPE_ORDER.map(x=>`<option value="${esc(x)}">${esc(x.replace('İbreli ',''))}</option>`).join('')}</select></div></section><section id="recordList" class="records">${recordCards(sortedRecords())}</section>`}
function recordCards(rows){if(!rows.length)return `<div class="empty card">Filtreye uygun istif bulunamadı.</div>`;return rows.map(r=>`<article class="record-card card" data-record="${r.id}"><span class="round-icon">${icons.logs}</span><div class="record-info"><span>Şeflik:</span><b>${esc(r.seflik.replace(' Şefliği',''))}</b><span>Bölme:</span><b>${esc(r.bolme)}</b><span>İstif:</span><b>${esc(r.istifNo)}</b><span>Tür:</span><b>${esc(r.type)}</b><span>Ster:</span><b>${esc(r.ster)} Ster</b><span>Tarih:</span><b>${trDate(r.date)}</b></div><div class="record-status ${r.coordinates?'':'warn'}"><div>${r.coordinates?icons.pin+' Koordinat Var':icons.pin+' Koordinat Bekleniyor'}</div><div>${icons.camera} ${r.photos?.length||r.photoCount||0} Fotoğraf</div><div>${icons.cloud} ${r.syncStatus==='synced'?'Senkronize':r.syncStatus==='drive_synced'?'Sunucu Bekliyor':r.syncStatus==='syncing'?'Yükleniyor':'Yerelde Kayıtlı'}</div></div></article>`).join('')}
function renderDocuments(){const bolmes=[...new Set(state.records.map(r=>r.bolme))];const chosen=sortedRecords(state.records.filter(r=>!state.builderBolme||r.bolme===state.builderBolme));return `${head('Evrak Oluştur','İstif seçimi yaparak evrak oluşturun',{action:`<button class="icon-btn">${icons.bell}</button>`})}<div class="segment"><button class="${state.documentTab==='photos'?'active':''}" data-doc-tab="photos">İstif Fotoğrafları</button><button class="${state.documentTab==='documents'?'active':''}" data-doc-tab="documents">Belgeler</button></div><div class="info-note"><b>${icons.info}</b><span>Aynı bölmedeki ve yakın tarihli istifleri seçin. Evrak sıralaması otomatik olarak kabuklu, lif, yakacak ve sırık şeklinde yapılır.</span></div><section class="builder-controls"><div class="select-panel card"><label class="select-row"><span class="round-icon">${icons.pin}</span><span class="row-copy"><small>Bölme Seç</small><select id="builderBolme" style="border:0;font-size:18px;font-weight:750;color:var(--green);background:transparent"><option value="">Tüm Bölmeler</option>${bolmes.map(x=>`<option ${state.builderBolme===x?'selected':''}>${esc(x)}</option>`).join('')}</select></span><span class="chev">›</span></label></div></section><div class="section-title"><h2>İstifler</h2><span>${state.selectedRecordIds.size} / ${chosen.length} seçildi</span></div><section class="builder-list card">${chosen.map(r=>`<label class="check-row"><input type="checkbox" data-record-check="${r.id}" ${state.selectedRecordIds.has(r.id)?'checked':''}><span>${icons.logs}</span><b>${esc(r.istifNo)} • ${esc(r.type)}</b></label>`).join('')}</section><div class="dual-actions"><button class="btn" data-action="select-all">${icons.check} Tümünü Seç</button><button class="btn" data-action="clear-selection">${icons.trash} Seçimi Temizle</button></div><div class="dual-actions"><button class="btn" data-action="preview-doc">${icons.eye} Önizle</button><button class="btn primary" data-action="print-doc">▤ PDF Oluştur</button></div><button class="btn wide" style="margin-top:9px" data-view="templates">Örnek Şablonları Gör</button>`}
function renderTemplates(){const sample=sortedRecords(state.records).slice(0,3);return `${head('Evraklar','Örnek şablonlar',{back:true,action:`<button class="icon-btn">${icons.bell}</button>`})}<section class="template-card card"><div class="template-title"><span class="round-icon">${icons.pin}</span><div><h3>Koordinat Evrakı</h3><p>Örnek koordinat tablosu</p></div></div>${miniCoordTable(sample)}</section><section class="template-card card"><div class="template-title"><span class="round-icon">${icons.camera}</span><div><h3>Fotoğraflı İstif Evrakı</h3><p>Örnek fotoğraf şablonu</p></div></div><div class="template-photo"><div class="mini-collage">${[1,2,3,4].map(()=>'<div class="ph"></div>').join('')}</div><div class="meta-list"><div><span>Şeflik:</span><b>Yaylacık</b></div><div><span>İstif:</span><b>İ-08</b></div><div><span>Tür:</span><b>İbreli Kabuklu Kağıtlık Odun</b></div></div></div></section><section class="template-card card"><div class="template-title"><span class="round-icon">${icons.doc}</span><div><h3>İstif Cins Listesi</h3><p>Örnek istif listesi</p></div></div>${miniTypeTable(sample)}</section><div class="dual-actions"><button class="btn" data-action="preview-doc">${icons.eye} Önizle</button><button class="btn primary" data-action="print-doc">▤ PDF Oluştur</button></div>`}
function miniCoordTable(rows){return `<table class="mini-table"><thead><tr><th>İstif No</th><th>Koordinat (Enlem, Boylam)</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.istifNo)}</td><td>${esc(r.coordinates||'Bekleniyor')}</td></tr>`).join('')}</tbody></table>`}
function miniTypeTable(rows){return `<table class="mini-table"><thead><tr><th>İstif No</th><th>İstif Cinsi (Tür)</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.istifNo)}</td><td>${esc(r.type)}</td></tr>`).join('')}</tbody></table>`}
function renderPhotos(){const rows=state.records.filter(r=>(r.photos?.length||r.photoCount||0)>0);return `${head('Fotoğraflar','İstif fotoğrafları ve Drive durumları',{back:true})}<section class="records">${rows.map(r=>`<article class="record-card card"><span class="round-icon">${icons.camera}</span><div class="record-info"><span>İstif:</span><b>${esc(r.istifNo)}</b><span>Tür:</span><b>${esc(r.type)}</b><span>Adet:</span><b>${r.photos?.length||r.photoCount||0}/4</b><span>Durum:</span><b>${r.syncStatus==='synced'?'Drive ve sunucu tamamlandı':'Yerelde saklanıyor'}</b></div><div class="record-status"><div>${icons.cloud} ${r.syncStatus==='synced'?'Tamamlandı':'Drive Bekliyor'}</div></div></article>`).join('')}</section>`}
function renderSettings(){return `${head('Ayarlar','Şeflik, ormancı ve senkronizasyon',{back:true})}<section class="settings-card card"><label>Varsayılan Şeflik</label><input id="setSeflik" value="${esc(state.settings.seflik)}"><label>Varsayılan Ormancı</label><input id="setOrmanci" value="${esc(state.settings.ormanci)}"><label>Google OAuth Client ID</label><input id="setClientId" value="${esc(state.settings.driveClientId)}" placeholder="...apps.googleusercontent.com"><label>Drive klasör ID (boşsa uygulama oluşturur)</label><input id="setFolderId" value="${esc(state.settings.driveFolderId)}" placeholder="İsteğe bağlı"><label>Sunucu kayıt adresi</label><input id="setServer" value="${esc(state.settings.serverEndpoint)}" placeholder="https://.../api/istif"><p class="settings-hint">Fotoğraflar sunucuya gönderilmez. Senkron sırasında Google Drive'a doğrudan yüklenir. OAuth Client ID gizli anahtar değildir; GitHub Pages adresinin Google Cloud tarafında yetkili origin olarak tanımlanması gerekir.</p><button class="btn primary wide" data-action="save-settings">Ayarları Kaydet</button></section><div class="info-note"><b>${icons.info}</b><span>Sürüm ${APP_VERSION} • Veriler IndexedDB içinde offline saklanır. Uygulama kamerası cihaz galerisine kayıt yapmaz.</span></div>`}
function bindDynamic(){
  app.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));
  app.querySelectorAll('[data-action="back"]').forEach(b=>b.onclick=()=>history.length>1?setView('home'):setView('home'));
  app.querySelector('[data-action="sync"]')?.addEventListener('click',syncAll);
  app.querySelector('[data-action="geo"]')?.addEventListener('click',getLocation);
  app.querySelectorAll('[data-add-photo]').forEach(b=>b.onclick=openCameraChooser);
  app.querySelectorAll('[data-remove-photo]').forEach(b=>b.onclick=()=>removePhoto(Number(b.dataset.removePhoto)));
  app.querySelector('#stackForm')?.addEventListener('input',e=>{if(e.target.name)ensureDraft()[e.target.name]=e.target.value});
  app.querySelector('#stackForm')?.addEventListener('submit',saveRecord);
  app.querySelector('[data-action="save-draft"]')?.addEventListener('click',e=>saveRecord(e,true));
  ['filterDate','filterBolme','filterType'].forEach(id=>app.querySelector('#'+id)?.addEventListener('change',applyRecordFilters));
  app.querySelectorAll('[data-doc-tab]').forEach(b=>b.onclick=()=>{state.documentTab=b.dataset.docTab;render()});
  app.querySelector('#builderBolme')?.addEventListener('change',e=>{state.builderBolme=e.target.value;state.selectedRecordIds.clear();render()});
  app.querySelectorAll('[data-record-check]').forEach(c=>c.onchange=()=>{c.checked?state.selectedRecordIds.add(c.dataset.recordCheck):state.selectedRecordIds.delete(c.dataset.recordCheck);render()});
  app.querySelector('[data-action="select-all"]')?.addEventListener('click',()=>{state.records.filter(r=>!state.builderBolme||r.bolme===state.builderBolme).forEach(r=>state.selectedRecordIds.add(r.id));render()});
  app.querySelector('[data-action="clear-selection"]')?.addEventListener('click',()=>{state.selectedRecordIds.clear();render()});
  app.querySelectorAll('[data-action="preview-doc"]').forEach(b=>b.onclick=previewDocuments);
  app.querySelectorAll('[data-action="print-doc"]').forEach(b=>b.onclick=printDocuments);
  app.querySelector('[data-action="save-settings"]')?.addEventListener('click',saveSettingsUI);
}
function applyRecordFilters(){const date=app.querySelector('#filterDate')?.value||'';const bolme=app.querySelector('#filterBolme')?.value||'';const type=app.querySelector('#filterType')?.value||'';const rows=sortedRecords(state.records.filter(r=>(!date||r.date===date)&&(!bolme||r.bolme===bolme)&&(!type||r.type.startsWith(type))));app.querySelector('#recordList').innerHTML=recordCards(rows)}
async function saveRecord(e,draftOnly=false){e?.preventDefault?.();const d=ensureDraft();if(!draftOnly&&(!d.bolme.trim()||!d.istifNo.trim()||!d.ster)){toast('Bölme, istif numarası ve ster sayısı zorunludur.','bad');return}d.photos=state.selectedPhotos.map(p=>({name:p.name,type:p.type,size:p.size,blob:p.blob}));d.photoCount=d.photos.length;d.syncStatus='local';d.updatedAt=new Date().toISOString();await idbPut('records',structuredClone(d));const i=state.records.findIndex(r=>r.id===d.id);if(i>=0)state.records[i]=structuredClone(d);else state.records.push(structuredClone(d));toast(draftOnly?'Taslak yerelde kaydedildi.':'İstif offline olarak kaydedildi.','good');state.draft=null;state.selectedPhotos=[];setView('records')}
function removePhoto(i){state.selectedPhotos.splice(i,1);render()}
function openCameraChooser(){if(state.selectedPhotos.length>=4){toast('En fazla 4 fotoğraf eklenebilir.','bad');return}openCamera().catch(()=>picker.click())}
async function openCamera(){
  if(!navigator.mediaDevices?.getUserMedia)throw new Error('Kamera desteklenmiyor');
  stopCamera();state.cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:state.facingMode},width:{ideal:1600},height:{ideal:1200}},audio:false});cameraVideo.srcObject=state.cameraStream;cameraModal.hidden=false;
}
function stopCamera(){state.cameraStream?.getTracks().forEach(t=>t.stop());state.cameraStream=null;cameraVideo.srcObject=null;cameraModal.hidden=true}
async function capturePhoto(){if(!cameraVideo.videoWidth)return;const c=document.createElement('canvas');c.width=cameraVideo.videoWidth;c.height=cameraVideo.videoHeight;c.getContext('2d').drawImage(cameraVideo,0,0);const blob=await compressCanvas(c,MAX_PHOTO_BYTES);addPhotoBlob(blob,`istif_${Date.now()}.jpg`);stopCamera();render();toast('Fotoğraf sıkıştırıldı ve uygulamaya eklendi.','good')}
async function compressCanvas(canvas,maxBytes){let maxDim=1600;let scale=Math.min(1,maxDim/Math.max(canvas.width,canvas.height));let work=document.createElement('canvas');work.width=Math.round(canvas.width*scale);work.height=Math.round(canvas.height*scale);work.getContext('2d',{alpha:false}).drawImage(canvas,0,0,work.width,work.height);let quality=.84,blob;for(let i=0;i<10;i++){blob=await new Promise(r=>work.toBlob(r,'image/jpeg',quality));if(blob&&blob.size<=maxBytes)return blob;if(quality>.48)quality-=.08;else{const next=document.createElement('canvas');next.width=Math.round(work.width*.84);next.height=Math.round(work.height*.84);next.getContext('2d',{alpha:false}).drawImage(work,0,0,next.width,next.height);work=next;quality=.72}}return blob}
async function compressFile(file){const img=await createImageBitmap(file);const c=document.createElement('canvas');c.width=img.width;c.height=img.height;c.getContext('2d').drawImage(img,0,0);img.close?.();return compressCanvas(c,MAX_PHOTO_BYTES)}
function addPhotoBlob(blob,name){if(state.selectedPhotos.length>=4)return;state.selectedPhotos.push({blob,name,type:'image/jpeg',size:blob.size})}
async function pickerChanged(){for(const f of [...picker.files]){if(state.selectedPhotos.length>=4)break;try{const b=await compressFile(f);addPhotoBlob(b,f.name.replace(/\.[^.]+$/,'.jpg'))}catch{toast('Fotoğraf işlenemedi.','bad')}}picker.value='';render()}
function getLocation(){if(!navigator.geolocation){toast('Konum özelliği desteklenmiyor.','bad');return}toast('Mevcut koordinat alınıyor...');navigator.geolocation.getCurrentPosition(p=>{ensureDraft().coordinates=`${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)}`;render();toast(`Koordinat eklendi • ±${Math.round(p.coords.accuracy)} m`,'good')},e=>toast('Konum alınamadı. GPS ve izinleri kontrol edin.','bad'),{enableHighAccuracy:true,timeout:15000,maximumAge:30000})}
function toast(msg,type=''){document.querySelector('.toast')?.remove();const t=document.createElement('div');t.className=`toast ${type}`;t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),3100)}
function showDialog(html){dialogContent.innerHTML=html;dialogModal.hidden=false}
function closeDialog(){dialogModal.hidden=true;dialogContent.innerHTML=''}
async function saveSettingsUI(){state.settings={...state.settings,seflik:document.getElementById('setSeflik').value.trim()||DEFAULT_SETTINGS.seflik,ormanci:document.getElementById('setOrmanci').value.trim()||DEFAULT_SETTINGS.ormanci,driveClientId:document.getElementById('setClientId').value.trim(),driveFolderId:document.getElementById('setFolderId').value.trim(),serverEndpoint:document.getElementById('setServer').value.trim()};await saveSettings();toast('Ayarlar kaydedildi.','good');setView('home')}
async function loadGoogleIdentity(){if(window.google?.accounts?.oauth2)return;await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=res;s.onerror=rej;document.head.appendChild(s)})}
async function getDriveToken(){await loadGoogleIdentity();return new Promise((resolve,reject)=>{const client=google.accounts.oauth2.initTokenClient({client_id:state.settings.driveClientId,scope:'https://www.googleapis.com/auth/drive.file',callback:r=>r.error?reject(new Error(r.error)):resolve(r.access_token),error_callback:reject});client.requestAccessToken({prompt:''})})}
async function driveJson(url,token,body){const r=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`Drive ${r.status}`);return r.json()}
async function ensureRootFolder(token){if(state.settings.driveFolderId)return state.settings.driveFolderId;if(state.settings.driveCreatedFolderId)return state.settings.driveCreatedFolderId;const f=await driveJson('https://www.googleapis.com/drive/v3/files?fields=id,name,webViewLink',token,{name:'Mesaha IO - İstif Alma',mimeType:'application/vnd.google-apps.folder'});state.settings.driveCreatedFolderId=f.id;await saveSettings();return f.id}
async function createFolder(token,name,parent){const f=await driveJson('https://www.googleapis.com/drive/v3/files?fields=id,name',token,{name,mimeType:'application/vnd.google-apps.folder',parents:parent?[parent]:undefined});return f.id}
async function uploadBlob(token,blob,name,parentId){const meta={name,parents:[parentId]};const boundary='mesaha_'+Math.random().toString(36).slice(2);const head=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(meta)}\r\n--${boundary}\r\nContent-Type: ${blob.type||'image/jpeg'}\r\n\r\n`;const tail=`\r\n--${boundary}--`;const body=new Blob([head,blob,tail],{type:`multipart/related; boundary=${boundary}`});const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':`multipart/related; boundary=${boundary}`},body});if(!r.ok)throw new Error(`Fotoğraf yükleme ${r.status}`);return r.json()}
async function syncAll(){
  if(state.syncing)return;const pending=state.records.filter(r=>r.syncStatus!=='synced');if(!pending.length){toast('Tüm kayıtlar senkronize.','good');return}
  if(!navigator.onLine){toast('İnternet yok. Kayıtlar cihazda güvende.','bad');return}
  if(!state.settings.driveClientId){showDialog(`<h3>Drive bağlantısı gerekli</h3><p>Gerçek Drive yüklemesi için Ayarlar bölümüne Google OAuth Client ID girilmelidir. Prototipte kayıtlar offline olarak cihazda korunuyor.</p><div class="dialog-actions"><button class="btn" data-dialog-close>Kapat</button><button class="btn primary" id="goSettings">Ayarlara Git</button></div>`);document.getElementById('goSettings').onclick=()=>{closeDialog();setView('settings')};return}
  state.syncing=true;showDialog(`<h3>Senkronizasyon</h3><p id="syncText">Google Drive bağlantısı kuruluyor…</p><div class="progress"><span id="syncBar"></span></div><div class="dialog-actions"><button class="btn" disabled>İptal</button><button class="btn primary" disabled>Devam Ediyor</button></div>`);
  try{const token=await getDriveToken();const root=await ensureRootFolder(token);let done=0,total=pending.length;for(const rec of pending){rec.syncStatus='syncing';await idbPut('records',rec);const folder=await createFolder(token,`${rec.date}_${rec.bolme}_${rec.istifNo}`,root);rec.driveFiles=[];for(let i=0;i<(rec.photos||[]).length;i++){const p=rec.photos[i];const up=await uploadBlob(token,p.blob,`${rec.istifNo}_foto_${i+1}.jpg`,folder);rec.driveFiles.push(up)}rec.driveFolderId=folder;rec.syncStatus='drive_synced';if(state.settings.serverEndpoint){const body={...rec,photos:undefined,driveFiles:rec.driveFiles};const rr=await fetch(state.settings.serverEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!rr.ok)throw new Error(`Sunucu kaydı ${rr.status}`);rec.syncStatus='synced'}await idbPut('records',rec);done++;document.getElementById('syncText').textContent=`${rec.istifNo} tamamlandı • ${done}/${total}`;document.getElementById('syncBar').style.width=`${done/total*100}%`}
    state.records=await idbGetAll('records');document.getElementById('syncText').textContent=state.settings.serverEndpoint?'Drive ve sunucu senkronizasyonu tamamlandı.':'Fotoğraflar Drive’a yüklendi. Sunucu adresi ayarlanmadığı için kayıt bilgileri bekliyor.';document.getElementById('syncBar').style.width='100%';setTimeout(()=>{closeDialog();render();toast('Senkronizasyon işlemi tamamlandı.','good')},1300)
  }catch(err){document.getElementById('syncText').textContent=`Bağlantı başarısız: ${err.message}. Yerel kayıtlar silinmedi.`;toast('Senkronizasyon tamamlanamadı.','bad')}finally{state.syncing=false}
}
function selectedForDocs(){let rows=state.records.filter(r=>state.selectedRecordIds.has(r.id));if(!rows.length)rows=sortedRecords(state.records).slice(0,4);return sortedRecords(rows)}
async function photoDataUrl(p){if(!p?.blob)return'';return new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(p.blob)})}
async function buildPrintHtml(){const rows=selectedForDocs();let html='';if(state.documentTab==='documents'){html+=`<div class="print-page"><h1>İSTİF KOORDİNAT LİSTESİ</h1><h2>Bölme: ${esc(rows[0]?.bolme||'')}</h2><table class="print-table"><thead><tr><th>Sıra</th><th>İstif No</th><th>İstif Cinsi</th><th>Ster</th><th>Koordinat</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.istifNo)}</td><td>${esc(r.type)}</td><td>${esc(r.ster)}</td><td>${esc(r.coordinates||'Bekleniyor')}</td></tr>`).join('')}</tbody></table><div class="print-footer">Mesaha İO • İstif Alma prototip şablonu</div></div>`;html+=`<div class="print-page"><h1>İSTİF CİNS LİSTESİ</h1><h2>Bölme: ${esc(rows[0]?.bolme||'')}</h2><table class="print-table"><thead><tr><th>Sıra</th><th>İstif No</th><th>Cinsi</th><th>Ster</th><th>Mevki</th><th>Barkod</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.istifNo)}</td><td>${esc(r.type)}</td><td>${esc(r.ster)}</td><td>${esc(r.mevki||'')}</td><td>${esc(r.barcode||'')}</td></tr>`).join('')}</tbody></table><div class="print-footer">Mesaha İO • İstif Alma prototip şablonu</div></div>`}
  if(state.documentTab==='photos'){for(const r of rows){const urls=await Promise.all((r.photos||[]).slice(0,4).map(photoDataUrl));html+=`<div class="print-page"><h1>FOTOĞRAFLI İSTİF EVRAKI</h1><div class="print-meta"><b>Şeflik:</b><span>${esc(r.seflik)}</span><b>Bölme:</b><span>${esc(r.bolme)}</span><b>İstif:</b><span>${esc(r.istifNo)}</span><b>Tür:</b><span>${esc(r.type)}</span><b>Ster:</b><span>${esc(r.ster)}</span><b>Koordinat:</b><span>${esc(r.coordinates||'Bekleniyor')}</span></div><div class="print-collage">${[0,1,2,3].map(i=>urls[i]?`<img src="${urls[i]}">`:`<div class="print-placeholder">Fotoğraf ${i+1}</div>`).join('')}</div><div class="print-footer">Mesaha İO • İstif Alma prototip şablonu</div></div>`}}
  return html}
async function previewDocuments(){const rows=selectedForDocs();showDialog(`<h3>${state.documentTab==='photos'?'İstif Fotoğrafları':'Belgeler'} Önizleme</h3><p>${rows.length} istif seçildi. Sıralama: kabuklu kağıtlık → lif yonga → yakacak → sırık.</p><div class="builder-list card">${rows.map(r=>`<div class="check-row"><span>${icons.logs}</span><b>${esc(r.istifNo)} • ${esc(r.type)}</b></div>`).join('')}</div><div class="dialog-actions"><button class="btn" data-dialog-close>Kapat</button><button class="btn primary" id="dialogPrint">PDF / Yazdır</button></div>`);document.getElementById('dialogPrint').onclick=()=>{closeDialog();printDocuments()}}
async function printDocuments(){const area=document.getElementById('printArea');area.innerHTML=await buildPrintHtml();area.setAttribute('aria-hidden','false');setTimeout(()=>window.print(),100)}

document.querySelectorAll('[data-close-camera]').forEach(x=>x.onclick=stopCamera);
document.querySelectorAll('[data-dialog-close]').forEach(x=>x.onclick=closeDialog);
dialogModal.addEventListener('click',e=>{if(e.target.matches('[data-dialog-close]'))closeDialog()});
document.getElementById('captureBtn').onclick=capturePhoto;
document.getElementById('pickGalleryBtn').onclick=()=>{stopCamera();picker.click()};
document.getElementById('switchCameraBtn').onclick=async()=>{state.facingMode=state.facingMode==='environment'?'user':'environment';try{await openCamera()}catch{toast('Kamera değiştirilemedi.','bad')}};
picker.addEventListener('change',pickerChanged);
window.addEventListener('online',()=>toast('İnternet bağlantısı geldi.','good'));
window.addEventListener('offline',()=>toast('Offline mod: kayıtlar cihazda tutuluyor.'));
window.addEventListener('afterprint',()=>{document.getElementById('printArea').innerHTML=''});

(async function init(){try{await loadData();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}catch(e){app.innerHTML=`<div class="empty"><h2>Uygulama açılamadı</h2><p>${esc(e.message)}</p></div>`}})();
