window.MESAHA_VERSION = {
  "app": "Mesaha İO",
  "version": "v569_yakupp",
  "build": 569,
  "visibleVersion": "V5.69 •Yakupp•",
  "shortVersion": "V5.69",
  "name": "Mesaha İO V5.69 •Yakupp•",
  "cacheName": "mio-app-v569-yakupp",
  "integrityId": "v569-offline-seflik-auth-recovery-r1",
  "builtAt": "2026-07-12T16:35:00+03:00",
  "notes": "Offline modda Şeflik Klasörüne girip çıkınca Google oturumunun bozulmuş görünmesi engellendi. İnternet geri gelince oturum sessiz yenilenir ve Şeflik Klasörü otomatik senkronize olur. Sürüm merkezi js/version.js üzerinden devam eder.",
  "assetVersion": "569",
  "latestVersion": "v569_yakupp",
  "latestBuild": 569,
  "currentBuild": 569,
  "minSupportedBuild": 409,
  "forceUpdate": false,
  "updateUrl": "./guncelle.html",
  "cleanUrl": "./temizle.html",
  "version_id": "v569_yakupp",
  "versionId": "v569_yakupp",
  "id": "v569_yakupp",
  "updated_at": "2026-07-12T16:35:00+03:00"
};
