window.MESAHA_VERSION = {
  "app": "Mesaha İO",
  "version": "v571_yakupp",
  "build": 571,
  "visibleVersion": "V5.71 •Yakupp•",
  "shortVersion": "V5.71",
  "name": "Mesaha İO V5.71 •Yakupp•",
  "cacheName": "mio-app-v571-yakupp",
  "integrityId": "v571-admin-avatar-update-safe-reset-r1",
  "builtAt": "2026-07-12T17:25:00+03:00",
  "notes": "Admin panelde Google profil fotoğrafları gösterilir. Güncelleme ekranı önbellek bütünlüğü takılırsa servis işçisini ve uygulama cachelerini güvenli temizleyip ana sayfayı açar. Supabase için güvenli bakım/sıfırlama SQL’i eklendi.",
  "assetVersion": "571",
  "latestVersion": "v571_yakupp",
  "latestBuild": 571,
  "currentBuild": 571,
  "minSupportedBuild": 409,
  "forceUpdate": false,
  "updateUrl": "./guncelle.html",
  "cleanUrl": "./temizle.html",
  "version_id": "v571_yakupp",
  "versionId": "v571_yakupp",
  "id": "v571_yakupp",
  "updated_at": "2026-07-12T17:25:00+03:00"
};
