window.MESAHA_VERSION = {
  "app": "Mesaha İO",
  "version": "v565_yakupp",
  "build": 565,
  "visibleVersion": "V5.65 •Yakupp•",
  "shortVersion": "V5.65",
  "name": "Mesaha İO V5.65 •Yakupp•",
  "cacheName": "mio-app-v565-yakupp",
  "integrityId": "v565-seflik-search-profile-one-owner-r1",
  "builtAt": "2026-07-12T14:55:00+03:00",
  "notes": "Ormancı eklemede 3 harften sonra öneri listesi eklendi. Her kullanıcı için tek şeflik kurma sınırı getirildi. Dosya şefliği alanı yeniden düzenlenebilir hale getirildi. Üst profil ve kullanıcı paneli sade ad-soyad/profil kartı görünümüne alındı.",
  "assetVersion": "565",
  "latestVersion": "v565_yakupp",
  "latestBuild": 565,
  "currentBuild": 565,
  "minSupportedBuild": 409,
  "forceUpdate": false,
  "updateUrl": "./guncelle.html",
  "cleanUrl": "./temizle.html",
  "version_id": "v565_yakupp",
  "versionId": "v565_yakupp",
  "id": "v565_yakupp",
  "updated_at": "2026-07-12T14:55:00+03:00"
};
