(function(){
  'use strict';
  var info={"app":"Mesaha İO","version":"v530_seflik_bolme_liste_ui_fix","build":530,"visibleVersion":"V5.30 •Şeflik FixX•","shortVersion":"V5.30","name":"Mesaha İO V5.30 •Şeflik FixX•","cacheName":"mesaha-app-v530-seflik-fix","builtAt":"2026-07-10T20:30:00+03:00","notes":"Bölme oluşturma sonrası anında listeleme, sunucu doğrulama fallbacki, Şeflik ekranı okunabilirlik ve Ölçümler buton sırası/renkleri düzeltildi.","assetVersion":"530","latestVersion":"v530_seflik_bolme_liste_ui_fix","latestBuild":530,"currentBuild":530,"minSupportedBuild":409,"forceUpdate":false,"updateUrl":"./guncelle.html","cleanUrl":"./temizle.html","version_id":"v530_seflik_bolme_liste_ui_fix","versionId":"v530_seflik_bolme_liste_ui_fix","id":"v530_seflik_bolme_liste_ui_fix","updated_at":"2026-07-10T20:30:00+03:00"};
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function applyToDocument(doc){doc=doc||document;try{doc.title=info.name;}catch(e){}try{doc.querySelectorAll('[data-version],[data-app-version]').forEach(function(el){el.textContent=info.visibleVersion;});}catch(e){}return info;}
  async function fetchRemote(){var url='./version.json?check='+Date.now();var ctrl=typeof AbortController!=='undefined'?new AbortController():null;var timer=ctrl?setTimeout(function(){ctrl.abort();},4500):0;try{var res=await fetch(url,{cache:'no-store',headers:{'Cache-Control':'no-cache'},signal:ctrl&&ctrl.signal});if(!res.ok)throw new Error('Sürüm bilgisi alınamadı: '+res.status);var remote=await res.json();return remote&&typeof remote==='object'?remote:null;}finally{if(timer)clearTimeout(timer);}}
  function isNewer(remote){if(!remote)return false;var rb=Number(remote.build||remote.latestBuild||0)||0;var cb=Number(info.build||0)||0;if(rb&&cb)return rb>cb;return !!(remote.version&&remote.version!==info.version);}
  var frozen=Object.freeze(info);window.MESAHA_VERSION=frozen;window.MESAHA_BUILD=530;window.MESAHA_VERSION_ID=info.version;window.MESAHA_VERSION_TEXT=info.visibleVersion;window.MESAHA_VERSION_SHORT=info.shortVersion;window.MesahaVersion={current:frozen,applyToDocument:applyToDocument,fetchRemote:fetchRemote,isNewer:isNewer,clone:clone};try{self.MESAHA_VERSION=frozen;self.MesahaVersion=window.MesahaVersion;}catch(e){}
})();
