(function(){'use strict';
const read=(k,f)=>{try{const x=JSON.parse(localStorage.getItem(k)||'null');return x==null?f:x}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}},clean=v=>String(v==null?'':v).trim();
function valid(){const s=read('mesaha_supabase_v500_session',{}),b=read('mesaha_supabase_v569_session_backup',{}),a=read('mesaha_google_access_v548',{}),t=read('mesaha_terminal_local_mode_v556',{})||read('mesaha_terminal_local_mode_v557',{});return !!(s.access_token||b.access_token||a.status==='approved'||t&&t.active)}
function css(){if(document.getElementById('suiteIstifCssV7'))return;const s=document.createElement('style');s.id='suiteIstifCssV7';s.textContent=`#bootOverlay,.boot-overlay,[data-action="refresh-shared"],[data-action="connect-drive"],[data-action="disconnect-drive"],[data-action="sync"],.drive-card,.drive-security{display:none!important}.suite-home-button{position:fixed!important;right:max(12px,env(safe-area-inset-right))!important;bottom:max(12px,env(safe-area-inset-bottom))!important;z-index:2147482000!important;border:0!important;border-radius:15px!important;padding:12px 15px!important;background:#fff!important;color:#174a32!important;box-shadow:0 10px 28px #0002!important;font-weight:800!important}.suite-istif-note-v7{margin:10px 0;padding:11px 13px;border-radius:13px;background:#edf7f0;color:#28543d;font:600 12px/1.45 system-ui}`;document.head.appendChild(s)}
function home(){if(document.getElementById('suiteHomeButtonV7'))return;const b=document.createElement('button');b.id='suiteHomeButtonV7';b.className='suite-home-button';b.type='button';b.textContent='⌂ Suite';b.onclick=()=>location.href='../';document.body.appendChild(b)}
function syncLocal(){const f=read('mesaha_active_seflik_folder_v564',{}),p=read('mesaha_panel_user_v316',{}),s=read('cam_mesaha_ayarlar_v1',{});if(f&&f.seflik){p.seflik=f.seflik;p.activeSeflik=f.seflik;s.seflik=f.seflik;write('mesaha_panel_user_v316',p);write('cam_mesaha_ayarlar_v1',s)}}
function hide(){document.querySelectorAll('[data-action="refresh-shared"],[data-action="connect-drive"],[data-action="disconnect-drive"],[data-action="sync"],.drive-card,.drive-security').forEach(x=>x.style.display='none');document.querySelectorAll('button,a').forEach(el=>{const t=clean(el.textContent).toLocaleLowerCase('tr-TR');if(/şeflik oluştur|şeflik sil|ormancı ekle|ormancı çıkar|bölme oluştur|bölme sil|drive bağla|bağlantıyı kaldır|şeflikleri yenile/.test(t))el.style.display='none'});const settings=document.querySelector('.settings-form,.settings-card');if(settings&&!document.getElementById('suiteIstifNoteV7')){const n=document.createElement('div');n.id='suiteIstifNoteV7';n.className='suite-istif-note-v7';n.textContent='Şeflik, ormancı, bölme, Drive, yedek ve senkronizasyon işlemleri Mesaha Suite ana menüsünden yönetilir. İstif İO içinde yalnızca Suite’ten gelen seçenekler kullanılır.';settings.insertBefore(n,settings.firstChild)}}
let timer=0;function schedule(){clearTimeout(timer);timer=setTimeout(()=>{syncLocal();hide();window.MesahaSuiteSyncV7&&window.MesahaSuiteSyncV7.updateButton()},120)}
function block(e){const t=e.target.closest&&e.target.closest('[data-action="refresh-shared"],[data-action="connect-drive"],[data-action="disconnect-drive"],[data-action="sync"]');if(!t)return;e.preventDefault();e.stopImmediatePropagation();if(t.matches('[data-action="sync"]'))window.MesahaSuiteSyncV7&&window.MesahaSuiteSyncV7.syncAll({source:'istif'});else location.href='../'}
if(!valid()){location.replace('../');return}window.MESAHA_SUITE_MODE=true;css();syncLocal();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{home();schedule()},{once:true});else{home();schedule()}document.addEventListener('click',block,true);window.addEventListener('storage',schedule);window.addEventListener('mesaha-suite:shared-data-updated',schedule);window.addEventListener('mesaha-suite:sync-complete',schedule);const watchSel='[data-action="refresh-shared"],[data-action="connect-drive"],[data-action="disconnect-drive"],[data-action="sync"],.drive-card,.drive-security,button,a';const mo=new MutationObserver(ms=>{for(const m of ms){for(const n of m.addedNodes){if(n.nodeType===1&&(n.matches&&n.matches(watchSel)||n.querySelector&&n.querySelector(watchSel))){schedule();return}}}});document.addEventListener('DOMContentLoaded',()=>mo.observe(document.getElementById('app')||document.body,{childList:true,subtree:true}),{once:true});setTimeout(schedule,350);setTimeout(schedule,1200);
})();
